### PR TITLE
Bug #375 - jface High-DPI: FileImageDescriptor's autoscaling strategy...

### PR DESCRIPTION
**Pull request by Dani-Hub**
..unnecessarily restricted to quadratic images

- Add in FileImageDescriptor#getxPath support for the more general rectangular image sizes
- Add test case

Signed-off-by: Daniel Krügler <daniel.kruegler@gmail.com>

### CODE REVIEW

**Comment by Dani-Hub** [comment]
Oops, what's going on here:

> Some blocking (most likely link/compilation) errors are present:
[FATAL] File AbstractObservable.java at line 19: The import org.eclipse.core.runtime cannot be resolved (location: /home/runner/work/eclipse.platform.ui/eclipse.platform.ui/bundles

Any suggestion what I did wrong here?

**Comment by laeubi** [comment]
@Dani-Hub I thing you can ignore this for now, maybe the GHaction is not configured correctly due to migration from Java 11 > Java 17, lets see what the jenkins CI build says here...

**Comment by Dani-Hub** [comment]
CI build seemed to be successful.

**Review by laeubi — APPROVED** [review]
Looks good.

**Pull request merged**
