### PR TITLE
Css background handler

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by vogella** [comment]
Ah... A GH action for version increases would be nice........... no idea if that would be possible to implement but this version increase stuff in time and build consuming. cc @HannesWell

**Comment by vogella** [comment]
Version update PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/117

**Comment by HannesWell** [comment]
> Ah... A GH action for version increases would be nice........... no idea if that would be possible to implement but this version increase stuff in time and build consuming. cc @HannesWell

I think it would be even better if the PDE API Tools were also capable to detect the need for service version-bumps. Then you would already notice it in the IDE.

That would require Apitools to have an extension-point/OSGi-service for build-qualifier-providers, that basically is asked for the build-qualifier of a given Project. Based on that Apitools can check if the build-qualifier changed in comparison to the baseline and without any version change and create a corresponding error in that case (just like it does for minor and major version changes due to API additions/breaks).
This is basically one thing [Tycho's compare-version-with-baselines mojo](https://www.eclipse.org/tycho/sitedocs/tycho-extras/tycho-p2-extras-plugin/compare-version-with-baselines-mojo.html) is doing.

With recent changes in M2E starts to support polyglot projects (https://github.com/eclipse-m2e/m2e-core/issues/119) and therefore probably could be a service-provider for such an `ProjectBuildQualifier` Service.

I had this idea a while already since I was just as annoyed as you are but did not yet have the time to propose it/work it out in more detail. But I plan to do that soon.

**Comment by akurtakov** [comment]
This hase caused in the I-build.

1. WARNING in /src/org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyBackgroundHandler.java 		 (at line 65) 		return retrieveCSSPropertyBackgroundAttachment(element, pseudo,      engine); 		The method retrieveCSSPropertyBackgroundAttachment(Object, String,  CSSEngine) from the type ICSSPropertyBackgroundHandler has been  deprecated and marked for removal
--
2. WARNING in /src/org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyBackgroundHandler.java 		 (at line 68) 		return retrieveCSSPropertyBackgroundColor(element, pseudo, engine); 		The method retrieveCSSPropertyBackgroundColor(Object, String,  CSSEngine) from the type ICSSPropertyBackgroundHandler has been  deprecated and marked for removal
3. WARNING in /src/org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyBackgroundHandler.java 		 (at line 70) 		return retrieveCSSPropertyBackgroundImage(element, pseudo, engine); 		The method retrieveCSSPropertyBackgroundImage(Object, String,  CSSEngine) from the type ICSSPropertyBackgroundHandler has been  deprecated and marked for removal
4. WARNING in /src/org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyBackgroundHandler.java 		 (at line 72) 		return retrieveCSSPropertyBackgroundPosition(element, pseudo,      engine); 		The method retrieveCSSPropertyBackgroundPosition(Object, String,  CSSEngine) from the type ICSSPropertyBackgroundHandler has been  deprecated and marked for removal
5. WARNING in /src/org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyBackgroundHandler.java 		 (at line 75) 		return retrieveCSSPropertyBackgroundRepeat(element, pseudo, engine); 		The method retrieveCSSPropertyBackgroundRepeat(Object, String,  CSSEngine) from the type ICSSPropertyBackgroundHandler has been  deprecated and marked for removal

**Comment by vogella** [comment]
I think https://github.com/eclipse-platform/eclipse.platform.ui/pull/115 will fix that.

**Comment by laeubi** [comment]
> That would require Apitools to have an extension-point/OSGi-service for build-qualifier-providers, that basically is asked for the build-qualifier of a given Project

One would better use the new [Tycho-CI-Friendly versions](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#enhanced-support-for-maven-ci-friendly-versions), it currently do not support _computing_ the minor version but that could be added thanks to the new maven extension

**Pull request merged**
