### PR TITLE
Revert highlighting fix

### PR DESCRIPTION
**Pull request by fedejeanne**
Revert #1690 

Due to #1955 , #1956 , https://github.com/eclipse-platform/eclipse.platform.swt/issues/1275

### CODE REVIEW

**Comment by iloveeclipse** [comment]
You cannot revert bundle versions for published bundles!

**Comment by iloveeclipse** [comment]
We have IBuild there with these versions.
The problem is that all new builds seeing IBuild versions will always pick the highest (broken) version of bundles.

@merks : WDYT, should we mark it unstable and revert versions, or better don't try to revert versions?

**Comment by akurtakov** [comment]
Please don't revert versions, everyone that already updated to latest I-build (I am aware and will redownload myself but others might not be) will not get updates.

**Comment by fedejeanne** [comment]
> Please don't revert versions, everyone that already updated to latest I-build (I am aware and will redownload myself but others might not be) will not get updates.

👍 
Done in 22dcffa4f1f6f97d2029c3b88e943e9ec40d94c3

**Comment by merks** [comment]
Yes, please don't revert versions.  These things have already escape and I are my pool.   Also, I think we can assume this will eventually be fixed properly and hence all the bundle will be incremented at some point in the not-to-distant future.

**Comment by fedejeanne** [comment]
> Yes, please don't revert versions. 

@merks versions should be as published now --> 22dcffa4f1f6f97d2029c3b88e943e9ec40d94c3

>  I think we can assume this will eventually be fixed properly and hence all the bundle will be incremented at some point in the not-to-distant future.

I'd say it should be possible to wait until later today to apply this PR and give @BeckerWdf / @Christopher-Hermann some time to find a better fix.

@iloveeclipse would that be ok for you? Since you are in Linux, you are seeing the problems in your IDE already. Colors can be changed though (see https://github.com/eclipse-platform/eclipse.platform.ui/pull/1690#issuecomment-2073052771), so it should be endurable for a couple of hours (?)

**Comment by fedejeanne** [comment]
> Please don't revert versions, everyone that already updated to latest I-build (I am aware and will redownload myself but others might not be) will not get updates.

Hm, on a second thought, this means that not only should I not revert (decrease) versions but I should actually **increase** versions, right @akurtakov ? I mean those who already updated their IDE and have #1690 in it should be able to get an update with #1957 (this PR) tomorrow. 

I'll increase versions in a separate commit in a minute.

**Comment by merks** [comment]
Yes, you should keep the versions as they are.  They should end up with a new qualifier in a new build via the other revert commit in the projects.

**Comment by mickaelistria** [comment]
> this means that not only should I not revert (decrease) versions but I should actually increase versions

No need to modify the x.y.z, the version qualifier will be increased at build-time because as it will be updated with the commit merge date, which would be newer.

**Comment by merks** [comment]
I'm okay with not doing a revert at all if this can be addressed in the next few hours.  Yesterday when was testing the removal of a feature, the build itself took like 3.5 hours and then the testing seemed to take another 4, so there is along delay between when you might commit a revert (without reverting versions) and a build from that being available.

**Comment by merks** [comment]
> > Please don't revert versions, everyone that already updated to latest I-build (I am aware and will redownload myself but others might not be) will not get updates.
> 
> Hm, on a second thought, this means that not only should I not revert (decrease) versions but I should actually **increase** versions, right @akurtakov ? I mean those who already updated their IDE and have #1690 in it should be able to get an update with #1957 (this PR) tomorrow.
> 
> I'll increase versions in a separate commit in a minute.

Just in case the rapid responses are not 100% clear, the idea is to revert everything **except the version changes** and as @mickaelistria correctly points out, this will result in new qualifier versions so that we can update to the reverted versions.

Hopefully the problem is just fixed very quickly...

---

I'm out for a few hours, otherwise I could test that the installer works with whatever fixes are being applied...

**Comment by iloveeclipse** [comment]
On Linux (and probably on other OSes) we have more problems that needs a fix: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1956 (wrong selection color, missing selection icon, missing foreground coloring on trees).

@Christopher-Hermann : if you could fix all of them today till evening, I can validate your fixes. 
Otherwise I would like to merge this revert for the next IBuild this night.

**Comment by Christopher-Hermann** [comment]
> @Christopher-Hermann : if you could fix all of them today till evening, I can validate your fixes. Otherwise I would like to merge this revert for the next IBuild this night.

Let's merge this revert. I will not mange to fix the issues by today.

**Comment by akurtakov** [comment]
FWIW, I strongly recommend testing colors issues/changes with both theming engine enabled and disabled, IMO it does a lot more than needed trying to workaround issues on lower lever thus breaking UI when an issue underneath is fixed.

**Comment by iloveeclipse** [comment]
> I strongly recommend testing colors issues/changes with both theming engine enabled and disabled

Exact. This is what I did on https://github.com/eclipse-platform/eclipse.platform.ui/issues/1956 and the problem appears in **both** modes.

**Comment by iloveeclipse** [comment]
I've quickly tested this PR and it fixes all the issues I've reported in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1956. So let's merge.

**Comment by iloveeclipse** [comment]
Should I trigger another IBuild now to see the real test results without JFace related errors?

**Comment by merks** [comment]
Yes please.

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/15/ started

**Pull request merged**
