### PR TITLE
Move "Light (Preview)" Theme to the "Light" Theme

### PR DESCRIPTION
**Pull request by BeckerWdf**
- Copies over all changes done in the "Light (Preview)" theme to the "Light" theme. So the changes done in the preview theme are now the default.

- Delete the "Light (Preview)" theme as it's no longer needed.

Also:
- Simplify the plugin.properties file to remove duplicated strings.

See: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

### CODE REVIEW

**Comment by BeckerWdf** [comment]
As discussed this PR does bring the changes done in the light preview theme to the "default" light theme (on all 3 SWT platforms). This is now done early in the 4.35 cycle to get further feedback and to have enough time to fix arising issues.

**Comment by vogella** [comment]
Looks great, lets merge this early in this release cycle so that we iron issue out during this release cycle.

Thanks a bunch @BeckerWdf .

**Comment by BeckerWdf** [comment]
CI Build says:

`Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.10:test (default-test) on project org.eclipse.ui.tests: An unexpected error occurred while launching the test runtime (process returned error code 13).`

What's wrong here?

**Comment by mickaelistria** [comment]
If you look at the log and scroll up to where `org.eclipse.ui.tests` is built and tests are run, you'll see
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Active Thread: Equinox Container: dbdc8da7-d7d6-4bc4-bb10-858d54a3575f"
Exception in thread "WorkbenchTestable" Exception in thread "Worker-6" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
An error has occurred. See the log file
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-2549/tests/org.eclipse.ui.tests/target/work/data/.metadata/.log.
```

**Comment by BeckerWdf** [comment]
> If you look at the log and scroll up to where `org.eclipse.ui.tests` is built and tests are run, you'll see
> 
> ```
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Active Thread: Equinox Container: dbdc8da7-d7d6-4bc4-bb10-858d54a3575f"
> Exception in thread "WorkbenchTestable" Exception in thread "Worker-6" java.lang.OutOfMemoryError: Java heap space
> java.lang.OutOfMemoryError: Java heap space
> An error has occurred. See the log file
> /home/jenkins/agent/workspace/eclipse.platform.ui_PR-2549/tests/org.eclipse.ui.tests/target/work/data/.metadata/.log.
> ```

So this is unrelated. I also don't expect that theme changes would cause failing tests. So let's merge this.

**Comment by mickaelistria** [comment]
Did you see any other build showing an OutOfMemery error before merging this patch?

**Comment by mickaelistria** [comment]
I tried a revert (#2559) to see whether the OOM was reproduced without the change, and it is reproduceable, so this particular change doesn't seem to blame.

**Comment by iloveeclipse** [comment]
OOM's seem to started recently. I've blamed infra but @HannesWell meant there were no changes. It would be nice if someone could investigate, I will be back to PC on Monday.

**Pull request merged**
