### PR TITLE
Issue #1103: Fix java doc

### PR DESCRIPTION
**Pull request by marcushoepfner**
Issue https://github.com/eclipse-platform/eclipse.platform.ui/issues/1103

Fix some java doc.

### CODE REVIEW

**Comment by marcushoepfner** [comment]
I still wonder... am I the only one who gets all the (javadoc) errors. 
Was something changed in the process of java doc generation?

I fixed some java doc errors and now get this:
```
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.e4.core.commands/src/org/eclipse/e4/core/commands/CommandServiceAddon.java:18: error: package javax.annotation does not exist
import javax.annotation.PostConstruct;
                       ^
``` 
Refer to https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-1207/9/consoleFull.

I tried to require bundle javax.annotation in Manifest.mf (instead of importing) but the build said, that the bundle could not be found. So I reverted this and I'm back to the above error now.

Any help is much appreciated since I have no clue what to do here.

**Comment by akurtakov** [comment]
It is probably similar cause to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8ac1938045fe8fb1e45738ea407909cb4e6b21cd where only latest version of a dep is resolved. Unfortunately, I can't dedicate the time to look into it more now.

**Comment by marcushoepfner** [comment]
> It is probably similar cause to [eclipse-platform/eclipse.platform.releng.aggregator@8ac1938](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8ac1938045fe8fb1e45738ea407909cb4e6b21cd) where only latest version of a dep is resolved. Unfortunately, I can't dedicate the time to look into it more now.

Ok. Do it mean, this need to be fixed? I wonder whether other builds fail.

I fixed a lot of issues in this commit but now I get this error in the pr-head build.
```
06:37:11.181 [ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/revisions/package.html:11: error: tag not supported in HTML5: tt
the <tt><a href="../../../text/revisions/package.html">org.eclipse.jface.text.revisions</a></tt>
    ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/source/package.html:10: error: tag not supported in HTML5: tt
Internal support classes and helpers for the <tt>org.eclipse.jface.text.source</tt> package.
                                             ^
2 errors
Command line was: /opt/tools/java/temurin/jdk-17/jdk-17.0.6+10/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/target/apidocs' dir.
``` 

I think I cannot fix this since it seem to be complaining about the generated html. So maybe something which need to be fixed in the java doc generator? Or configured differently?!

Do you think I can merge this commit? Maybe you could kindly review.

**Comment by akurtakov** [comment]
> > It is probably similar cause to [eclipse-platform/eclipse.platform.releng.aggregator@8ac1938](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8ac1938045fe8fb1e45738ea407909cb4e6b21cd) where only latest version of a dep is resolved. Unfortunately, I can't dedicate the time to look into it more now.
> 
> Ok. Do it mean, this need to be fixed? I wonder whether other builds fail.
> 
> I fixed a lot of issues in this commit but now I get this error in the pr-head build.
> 
> ```
> 06:37:11.181 [ERROR] MavenReportException: Error while generating Javadoc: 
> Exit code: 1
> /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/revisions/package.html:11: error: tag not supported in HTML5: tt
> the <tt><a href="../../../text/revisions/package.html">org.eclipse.jface.text.revisions</a></tt>
>     ^
> /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/source/package.html:10: error: tag not supported in HTML5: tt
> Internal support classes and helpers for the <tt>org.eclipse.jface.text.source</tt> package.
>                                              ^
> 2 errors
> Command line was: /opt/tools/java/temurin/jdk-17/jdk-17.0.6+10/bin/javadoc @options @packages
> 
> Refer to the generated Javadoc files in '/home/jenkins/agent/workspace/eclipse.platform.ui_PR-1207/bundles/org.eclipse.jface.text/target/apidocs' dir.
> ```
> 
> I think I cannot fix this since it seem to be complaining about the generated html. So maybe something which need to be fixed in the java doc generator? Or configured differently?!

Actually these are not generated files - you have to edit https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/revisions/package.html and https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface.text/src/org/eclipse/jface/internal/text/source/package.html to replace tt tag with code tag. This can and probably should be done in separate tag so changes are smaller and easier to review and easier to grasp.

> 
> Do you think I can merge this commit? Maybe you could kindly review.

I'll review this one

**Comment by akurtakov** [comment]
Build fails with :
```
06:37:35.253 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.4-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.workbench3: Only qualifier changed for (org.eclipse.e4.ui.workbench3/0.17.100.v20231024-0631). Expected to have bigger x.y.z than what is available in baseline (0.17.100.v20230727-0604) -> [Help 1]
```
This should be fixed before merging.

**Comment by marcushoepfner** [comment]
package html is fixed in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1242

**Comment by marcushoepfner** [comment]
> org.eclipse.e4.ui.workbench3

done, increased from 0.17.100 to 0.18.0

**Comment by iloveeclipse** [comment]
> increased from 0.17.100 to 0.18.0

Why that? Have you added new API? If nkt, 0.17.200 would be the right version

**Comment by marcushoepfner** [comment]
I split commit.
jface changes are here: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1244.

**Comment by marcushoepfner** [comment]
Unit test error does not belong to this commit but there is an issue already: https://github.com/eclipse-platform/eclipse.platform.ui/issues/275.

I'm going to merge tomorrow if no one complains.

**Pull request merged**
