### PR TITLE
Close test windows in ImportArchiveOperationTest

### PR DESCRIPTION
**Pull request by akurtakov**
Work towards
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2432 .

### CODE REVIEW

**Comment by jukzi** [comment]
Could you please check the whole UiTestSuite if there are more tests that leak windows?

**Comment by akurtakov** [comment]
I will try to find time for it but not promising fast reaction.

**Comment by iloveeclipse** [comment]
```
Results:
Tests run: 1660, Failures: 0, Errors: 0, Skipped: 196
Exception in thread "Worker-10" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Active Thread: Equinox Container: fc315e41-540a-4943-99bc-5124c96902d1" java.lang.OutOfMemoryError: Java heap space
Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:[4837](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-2610/1/pipeline-console/?start-byte=1579339&selected-node=34#log-4837))
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:118)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:38)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Active Thread: Equinox Container: fc315e41-540a-4943-99bc-5124c96902d1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-22"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-2"
```

Same as in https://github.com/eclipse-platform/eclipse.platform.ui/pull/2433.
In https://github.com/eclipse-platform/eclipse.platform.ui/pull/2433 we see the memory is OK after the UiTestsuite and explodes after

```
#################################################
testOpenCloseView
########### Memory usage reported by JVM ########
   1.073.741.824 bytes max heap
   1.073.741.824 bytes heap allocated
     688.209.928 bytes free heap
     385.531.896 bytes used heap
#################################################

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.50 s -- in UiTestSuite org.eclipse.ui.tests.stress.OpenCloseTest
org.eclipse.ui.tests.stress.OpenCloseTest.testOpenClosePerspective -- Time elapsed: 4.625 s
org.eclipse.ui.tests.stress.OpenCloseTest.testOpenCloseIntro -- Time elapsed: 1.030 s
org.eclipse.ui.tests.stress.OpenCloseTest.testOpenCloseWorkbenchWindow -- Time elapsed: 5.930 s
org.eclipse.ui.tests.stress.OpenCloseTest.testOpenCloseFile -- Time elapsed: 2.372 s
org.eclipse.ui.tests.stress.OpenCloseTest.testOpenCloseView -- Time elapsed: 1.546 s
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 843.1 s -- in org.eclipse.ui.tests.UiTestSuite

Results:

Tests run: 1660, Failures: 0, Errors: 0, Skipped: 196

Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:119)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:38)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:80)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by akurtakov** [comment]
Merging it despite the failure. IMO it's a classic case of death by thousand paper cut and a big overhaul of the test suite will be needed before it reduces requirements.

**Pull request merged**
