### PR TITLE
Fix the layout of new workspace label for unexpected path

### PR DESCRIPTION
**Pull request by laeubi**
Currently the label is combined with the combo what gives strange results.

This moves the label out of the this into an own row and also hide it if there is no information to show.

### CODE REVIEW

**Comment by elsazac** [comment]
Thanks @laeubi for the PR. The layout looks good. I have tested this only on Mac and one thing that I noticed is, the warning symbol isn't shown.

image

**Comment by laeubi** [comment]
I don't know where the warning symbol is supposed to come from but at least under SWT I haven't seen it before. If we really want a warning icon ist maybe better to use a decorator on the combo or similar, for now I would just go without it.

**Comment by laeubi** [comment]
@elsazac the warning is now back!

This is how it looks on linux
grafik

**Comment by elsazac** [comment]
> @elsazac the warning is now back!

Yes. I can see that now. This looks good to me. 
Thanks @laeubi

**Comment by merks** [comment]
It (Switch workspace) looks like this on Windows:

image

**Comment by iloveeclipse** [comment]
Let's merge that, it is by any means better as current state.

**Pull request merged**
