### PR TITLE
[a11y] - Content Types Preference description can't be read by JAWS

### LINKED ISSUE #287: [a11y] - Content Types Preference description can't be read by JAWS
Steps to reproduce on Windows:
1. Open JAWS
2. Launch Eclipse
3. Click Window > Preferences > General > Content Types
Eclipse_Preference_ContentType_JAWS

===== EXPECTED RESULT =====
The content should be read out for user.

### LINKED ISSUE #340: [a11y] - Content Types Preference description can't be read by JAWS
Steps to reproduce on Windows:
1. Open JAWS
2. Launch Eclipse
3. Click Window > Preferences > General > Content Types
Eclipse_Preference_ContentType_JAWS

===== EXPECTED RESULT =====
The content should be read out for user.

### PR DESCRIPTION
**Pull request by niraj-modi**
- Fixes eclipse-platform/eclipse.platform.swt#340 

Signed-off-by: Niraj Modi <niraj.modi@in.ibm.com>

### CODE REVIEW

**Review by niraj-modi — COMMENTED** [review]
Changes are very narrow to Accessibility use-case only.

**Comment by akurtakov** [comment]
Should we consider making this change by default in SWT's Link widget by default ?

**Comment by lshanmug** [comment]
Problem seems specific to JAWS/Windows as it works as expected with VoiceOver on Mac.

**Comment by niraj-modi** [comment]
> Problem seems specific to JAWS/Windows as it works as expected with VoiceOver on Mac.

Thanks Lakshmi for confirming the MAC behavior.

> Should we consider making this change by default in SWT's Link widget by default ?

Yes, fixing in SWT will improve the default behavior and also the issue seems specific to Windows only.

I plan to transfer this issue to SWT and make a fix in SWT Windows port only for RC1.

**Comment by niraj-modi** [comment]
Closing this PR in favor of https://github.com/eclipse-platform/eclipse.platform.swt/pull/341

**Pull request closed without merging**
