### PR TITLE
Rename Generic Text Editor into Generic Code Editor

### LINKED ISSUE #1385: Relabel "Generic Editor" (or "Advanced Text Editor")
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

Here and there, we see references to "Generic Editor" or "Advanced Text Editor". The first one is not really user-oriented as the name is more related to the internals of the Editor and it doesn't tell much about what it can do better; the second tries to emphasize that it should be preferred, but it doesn't tell much about what cases it's supposed to serve better.
So I would recommend that we consider a better label for this editor.
I currently have 2 suggestions:
* Generic Code Editor
* Generic Source Editor

I like keeping the "Generic" to emphasize that there can be some better specialized editors, but telling "Code" or "Source" also tells that some convenience features for developers (brackets matching, collapse range...) can already be available for this editor.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

### PR DESCRIPTION
**Pull request by mickaelistria**
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/1532 and https://github.com/eclipse-platform/eclipse.platform.ui/issues/1385

### CODE REVIEW

**Comment by vogella** [comment]
I would drop the "Generic". "Code Editor" or "Text Editor" (if the old one is renamed) is short and IMHO less confusing for the user.

**Comment by mickaelistria** [comment]
Let's go incrementally. Choosing a name never is a consensual exercise, going baby steps is more likely to create progress.
Moreover, the "Generic Code Editor" is usually a good fit for "generic code edition", but if there is a dedicated editor (eg "Java editor"), then the "Generic Code Editor" seems a bit too generic as it wouldn't provide as many language features. So Generic is not too harmful at the moment.

**Comment by vogella** [comment]
I'm fine with the incremental change idea. Change is fine for me.

**Comment by merks** [comment]
I wonder if the end-user considers *.html, *.xm, or *.target to be code?  (I dislike naming discussions; you can never please everyone.   But I really wonder what is code and what is not code?

**Comment by mickaelistria** [comment]
> But I really wonder what is code and what is not code?

I don't know if this even can have an answer :shrug: My interpretation is that any textual language that's not prose is more or less code. ie if it's not meant to talk to directly to a human and if the language is tailored first for a machine to understand or manipulate or executre or render... it, it's code to me.

**Comment by mickaelistria** [comment]
One more argument in favor of "Code" is that many people use Visual Studio Code (executable is `code`) to edit their HTML files and AFAIK there has been no argument that the name wasn't suitable.

**Comment by HannesWell** [comment]
> I would drop the "Generic". "Code Editor" or "Text Editor" (if the old one is renamed) is short and IMHO less confusing for the user.

I would also be fine with just `Text Editor`and `Code Editor`. If I read the later I would expect that the editor can handle 'codish' content.
That the editor is a generic `Code Editor` seems to be implied for me because a generic name like `Code` is used.

And I would also expect that an editor that is named more specifically can handle that specific thing better.
I.e. when having a `Code Editor` and a `Java Editor` I would expect the later to handle Java files best. 

That's just my 2ct. If the majority prefers `Generic Code Editor` I would also be fine.

**Pull request merged**
