### PR TITLE
Update Notification API to use modern looking X

### LINKED ISSUE #2035: find/replace overlay - Notification API uses old X
I haven't seen the notification API in a while, unfortunately the idea that we use it in the Eclipse IDE for non-blocking information seems not to have captured any interested and we removed it from theme switching as a restart is required.

So I'm happy to see it in the find/replace development.

image

Unfortunately the pop-up uses the old Eclipse IDE close button which we discussed a very long time and decided that this X is very, very ugly.

@BeckerWdf IIRC we both discussed its replacement in the past. Could you create a PR for the replacement? I think it is a svg / png file.

### PR DESCRIPTION
**Pull request by vogella**
The find/replace overlay introduces a new close icon similar to the close icon used for the tab folder from
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575395

This pull request updates the notification close icon which still looks like the old tab icon before the change in
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575395  and does not fit anymore in the overall look and feel.

A follow-up PR could also update the active folder but find a new "reddisch" color would require more testing on the different OS, while with the regular icon we can build on the testing of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1991

Fixes: #2035

### CODE REVIEW

**Comment by BeckerWdf** [comment]
can you please post before and after screenshots?

**Comment by vogella** [comment]
> can you please post before and after screenshots?

You see the icons here: https://github.com/eclipse-platform/eclipse.platform.ui/pull/2037/files. It this sufficient?

**Comment by BeckerWdf** [comment]
I meant screenshot of the notification before and after.
Best in light and dark theme. 
Just like @HeikoKlare always does it.

**Comment by Wittmaxi** [comment]
Should we also update the .images repository?

**Comment by BeckerWdf** [comment]
> Should we also update the .images repository?

Yes please.

**Comment by vogella** [comment]
New Light:

image

New Dark:

image


Old Light:

image


Old Dark:

image

As you notice the notification ignores the styling, independent of the icon. I never noticed that before that that is an unrelated issue.

**Comment by HeikoKlare** [comment]
I just tested the PR and with my setup (running the `NotificationPopupTest` on Windows) the popup actually adapts to the theme. Here is what is looks like:
Screenshot 2024-07-05 154955
image

In any case, the icon looks fine for me, even though it could be a bit lighter.

**Review by BeckerWdf — APPROVED** [review]

**Comment by vogella** [comment]
> In any case, the icon looks fine for me

thanks :-)

**Comment by vogella** [comment]
> > Should we also update the .images repository?
> 
> Yes please.

@HeikoKlare once you add your svg to the image repo, can you also also add a copy to the notification project?

**Comment by HeikoKlare** [comment]
> @HeikoKlare once you add your svg to the image repo, can you also also add a copy to the notification project?

I have already added the close icon for the find/replay overlay to the images repo (https://github.com/eclipse-platform/eclipse.platform.images/pull/80), but I can, of course, create another PR for also adding the icon to the jface.notifications project.

When trying to do so, I found that there is also an "active" version of the icon, which is used when hovering over it. We need to adapt this too, as currently the old icon is still used when hovering (and I do not think that we can easily get rid of it, as we hovering feedback has to be implemented in some way):
notification_close_active

I will have a look and try to provide a proper new "active" icon.

**Comment by Wittmaxi** [comment]
@HeikoKlare related to my report in #2043

**Comment by HeikoKlare** [comment]
> @HeikoKlare related to my report in #2043

Thanks! I missed that one.

**Pull request merged**
