### PR TITLE
Jface high dpi file image descriptor's autoscaling rounding different from that of dpi util#auto scale image data #378

### PR DESCRIPTION
**Pull request by Dani-Hub**

### CODE REVIEW

**Comment by Dani-Hub** [comment]
Sigh - I don't understand why now suddenly this huge number of file changes has entered my pull request. I had created a separate branch and did only two edits and one file addition.

**Comment by Dani-Hub** [comment]
I will it a new trial

**Comment by laeubi** [comment]
Make sure you

1. Have pulled all updates from the "upstream" that is [eclipse-platform:master](https://github.com/eclipse-platform/eclipse.platform.ui)
2. When you create a new branch, create it from [eclipse-platform:master](https://github.com/eclipse-platform/eclipse.platform.ui) 

Beside that you can try to reset your fork master brnach to the remote upstream one:
https://stackoverflow.com/questions/42332769/how-do-i-reset-the-git-master-branch-to-the-upstream-branch-in-a-forked-reposito

**Comment by Dani-Hub** [comment]
Thanks again. I took advantage of your recently presented rebase+squash technique and will later cleanup my own repo.

**Pull request closed without merging**
