### PR TITLE
Spacing for onboarding control can be decreased

### PR DESCRIPTION
**Pull request by BeckerWdf**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
At least on macOS 2px spacing are sufficient instead of 50 px. Does this also work for windows and linux?

**Comment by iloveeclipse** [comment]
That's not enough on Linux. I had to set 30 px to see full borders on the "title" of the empty area.
With 2px it looks like this:
image

**Comment by BeckerWdf** [comment]
> That's not enough on Linux. I had to set 30 px to see full borders on the "title" of the empty area. With 2px it looks like this: image

Ok. On macOS we don't have that second line. I set it to 30 px and updated #705 . Can you pls. test again?

**Comment by BeckerWdf** [comment]
I could improve it even further by using different spacing on the different sides.

**Comment by iloveeclipse** [comment]
> I set it to 30 px and updated #705 . Can you pls. test again?

OK for me now.

**Comment by iloveeclipse** [comment]
Note, I've slightly refactored the code and also already moved constant definition / set to 30 pixel in https://github.com/eclipse-platform/eclipse.platform.ui/pull/709.

So this PR has to be manually rebased / adopted on latest master.

**Comment by BeckerWdf** [comment]
> Note, I've slightly refactored the code and also already moved constant definition / set to 30 pixel in #709.
> 
> So this PR has to be manually rebased / adopted on latest master.

Thanks for that. I updated the PR. And I also improved the icon once again (so longer so thick lines). I think now it looks good.

**Comment by iloveeclipse** [comment]
@BeckerWdf : the constant I've added (any you've renamed / made private) was used in tests. These tests don't compile anymore now and most likely will need another fix after your changes.

**Comment by BeckerWdf** [comment]
> @BeckerWdf : the constant I've added (any you've renamed / made private) was used in tests. These tests don't compile anymore now and most likely will need another fix after your changes.

Should be fixed now

**Comment by iloveeclipse** [comment]
> Should be fixed now

Looks OK for me on Linux. Can you also update images added for Java & Co perspectives?

**Comment by BeckerWdf** [comment]
> Can you also update images added for Java & Co perspectives?

Yes I will.

**Comment by BeckerWdf** [comment]
I see:
"Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.0-SNAPSHOT:test (default-test) on project org.eclipse.ui.monitoring.tests: There are test failures."

What does that mean? I assume this is not related to my change.

**Comment by iloveeclipse** [comment]
> I see:
> "Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.0-SNAPSHOT:test (default-test) on project org.eclipse.ui.monitoring.tests: There are test failures."

**Where** do you see that? Can you please add link?

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
The code is OK, but none of the commits point to the https://github.com/eclipse-platform/eclipse.platform.ui/issues/702

Please could you amend commits and add line to the commit messages

`Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/702`
or
`See https://github.com/eclipse-platform/eclipse.platform.ui/issues/702`

Navigation from the commit in the Git History in Eclipse to the PR without such reference is really painful without and could be a single click with such reference.

**Comment by BeckerWdf** [comment]
> Please could you amend commits and add line to the commit messages

Done

**Review by iloveeclipse — APPROVED** [review]
Thanks.

**Comment by BeckerWdf** [comment]
> > I see:
> > "Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.0-SNAPSHOT:test (default-test) on project org.eclipse.ui.monitoring.tests: There are test failures."
> 
> **Where** do you see that? Can you please add link?

https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4667002133/jobs/8262248692?pr=705

**Comment by iloveeclipse** [comment]
> > > I see:
> > > "Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.0-SNAPSHOT:test (default-test) on project org.eclipse.ui.monitoring.tests: There are test failures."
> > 
> > 
> > **Where** do you see that? Can you please add link?
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4667002133/jobs/8262248692?pr=705

OK, this is the [well known problem](https://github.com/eclipse-platform/eclipse.platform.ui/issues/688) of gh-actions that confuses everyone.

GitHub actions do not work right now, they fails with different test fails on different platforms.
The only working is "continuous-integration/jenkins/pr-head" action that runs tests on Eclipse.org jenkins instance.
So if  "continuous-integration/jenkins/pr-head" is OK, we should be fine.

**Comment by BeckerWdf** [comment]
> > Can you also update images added for Java & Co perspectives?
> 
> Yes I will.

See: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/516

**Pull request merged**
