### PR TITLE
Add KeyAssistDialogTest to test suite

### LINKED ISSUE #665: Unit test errors in github validation builds
Refer to #662 

There are unit test failures in:
- **Windows** org.eclipse.jface.tests.notifications.NotificationPopupTest
```
Expected: a collection containing is <Text {}>
     but: was <List {}>
java.lang.AssertionError: 

Expected: a collection containing is <Text {}>
     but: was <List {}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.eclipse.jface.tests.notifications.NotificationPopupTest.createsWithTextContent(NotificationPopupTest.java:100)
```
- **Windows** org.eclipse.ui.internal.monitoring.EventLoopMonitorThreadTests
```
A freeze event didn't capture a good range of stack samples (462) expected:<5> but was:<1>
java.lang.AssertionError: A freeze event didn't capture a good range of stack samples (462) expected:<5> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.ui.internal.monitoring.EventLoopMonitorThreadTests.testEventLogging(EventLoopMonitorThreadTests.java:358)
```
- **Windows** org.eclipse.ui.internal.ide.application.FileLocationDetailsTest (several)
```
Illegal char <:> at index 87: C:\Users\RUNNER~1\AppData\Local\Temp\FileLocationDetailsTest3143935122662222144java+178:3
java.nio.file.InvalidPathException: Illegal char <:> at index 87: C:\Users\RUNNER~1\AppData\Local\Temp\FileLocationDetailsTest3143935122662222144java+178:3
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.eclipse.core.internal.filesystem.local.nio.DosHandler.fetchFileInfo(DosHandler.java:42)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.fetchFileInfo(LocalFileNativesManager.java:65)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:161)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:260)
	at org.eclipse.ui.internal.ide.application.FileLocationDetails.checkLocation(FileLocationDetails.java:105)
	at org.eclipse.ui.internal.ide.application.FileLocationDetails.resolve(FileLocationDetails.java:63)
	at org.eclipse.ui.internal.ide.application.FileLocationDetailsTest.testLineAsPlus_ColumnAsColon(FileLocationDetailsTest.java:81)
```

They seem to be in the main branch.

### PR DESCRIPTION
**Pull request by oleosterhagen**
Sorry, with PR #655 I forgot to add a newly introduced test to the test suite in the Java package.

The test was already found and invoked by the Tycho Surefire Plugin during the Maven build. But it is missing from the [published test reports](https://download.eclipse.org/eclipse/downloads/) since these are produced by a separate Ant build using manually created test suites.

### CODE REVIEW

**Comment by vogella** [comment]
Thanks for the follow-up. If Linux verification build goes green I will merge, for Windows and MacOS we currently have issues, see https://github.com/eclipse-platform/eclipse.platform.ui/issues/665

**Comment by oleosterhagen** [comment]
> If Linux verification build goes green I will merge, for Windows and MacOS we currently have issues, see #665

Unfortunately, the Linux build has also a test failure:

```
EventLoopMonitorThreadTests.testDoublyNestedEventLogging:425 A freeze event didn't capture a good range of stack samples (660) expected:<5> but was:<1>
```

Yesterday a commit on master had problems in the same test class - but in a different method:

```
EventLoopMonitorThreadTests.testEventLogging:358 A freeze event didn't capture a good range of stack samples (330 396 462) expected:<5> but was:<3>
```

**Comment by vogella** [comment]
Seems to fail on all platforms. @oleosterhagen  can you have a look?

**Comment by oleosterhagen** [comment]
I have changed the helper methods in the class EventLoopMonitorThreadTests to stabilize the tests. In the actual test methods I have only eliminated the no longer needed synchronized blocks. This leads to many white space only changes.

**Comment by oleosterhagen** [comment]
@vogella, I have rebased this branch. The `EventLoopMonitorThreadTests` seem now to be stable. But there are still some unrelated failing tests on Linux and Windows. I think these should be handled with separate pull requests.

**Review by HannesWell — COMMENTED** [review]
Thank you @oleosterhagen for this PR, it is great to have all tests fixed for all platforms (hopefully, but the all green checks look very promising 😃 ). Locally the tests pass on my computer and I assumed that one could increase the freeze-time to achieve the desired result. But your approach looks more robust.

After a quick look at it in the web UI it looks reasonable, but I can have a more detailed review probably tomorrow.

Have you considered to use a `CountDownLatch` or a `CyclicBarrier`? This might save the loop and the manual synchronization?

**Comment by HannesWell** [comment]
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/665

**Comment by oleosterhagen** [comment]
Using a `CyclicBarrier` is a very good suggestion. This simplifies the implementation of the new `ThreadControl` class.

**Comment by oleosterhagen** [comment]
After pushing the changes, I now see two more unrelated issues:

1. The `SorterTest` failed. This one I already have seen a few times. For example yesterday on master: [Workflow Run](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4843446791/jobs/8631076743)

```
org.eclipse.ui.tests.navigator.SorterTest.testSorterContentAdd  Time elapsed: 0.37 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Blue[Added]Parent> but was:<Blue[]Parent>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.ui.tests.navigator.SorterTest.testSorterContentAdd(SorterTest.java:291)
```

2. A problem while publishing the test results: [Workflow Run](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4845607968)

`Get "https://pipelines.actions.githubusercontent.com/serviceHosts/cfadb002-5275-420b-a8dd-8043a22417b6/_apis/pipelines/1/runs/2864/signedartifactscontent?artifactName=test-results-ubuntu-latest&urlExpires=2023-04-30T17%3A42%3A03.6555187Z&urlSigningMethod=HMACV2&urlSignature=FfvE283%2BzTKli3M48W7EVhcQ%2Fqt9kcw92cgYqZRRKXg%3D": dial tcp 13.107.42.16:443: i/o timeout`

**Review by HannesWell — APPROVED** [review]
This change looks good.

If you want/can address the other intermittent test-failures, please create a follow up PR.
Regarding the workflow failure, I assume that this is just a temporary hick-up. I just restarted all jobs, maybe this time the test result upload succeeds. If it still fails please just (force-) push your branch with a changed head commit (you can just amend it locally without any real change) so that the workflow is completely triggered again.

**Comment by HannesWell** [comment]
All checks were green this time. Thank you @oleosterhagen!

**Comment by oleosterhagen** [comment]
@HannesWell, thank you very much for your review and suggestions!

**Pull request merged**
