### PR TITLE
Use multi-line String in CSS tests

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by marcushoepfner** [comment]
There are test methods which have only two lines css (e.g. CascadeTests).
However, can you change them as well. With that, it is consistent in all methods. And the "\n" is gone.

**Comment by jukzi** [comment]
please provide a commit message. Is that an automated conversion?

**Comment by vogella** [comment]
> There are test methods which have only two lines css (e.g. CascadeTests). However, can you change them as well. With that, it is consistent in all methods. And the "\n" is gone.

Will do that with another commit, this one was done with the automatic JDT cleanup and I think it is bad to mix automatic changes with manual changes.

**Comment by vogella** [comment]
> please provide a commit message. Is that an automated conversion?

Done

**Comment by marcushoepfner** [comment]
I think the two failed tests are flickering.
I retrigger the build to check this

**Comment by vogella** [comment]
@HeikoKlare in case you are intested also in helping with test stability in eclipse.platform.ui (which would be great), we see "random" errors on a regular basis in our PR in this repo too.

**Review by marcushoepfner — APPROVED** [review]

**Pull request merged**
