### PR TITLE
Improvement to the existing dark theme

### PR DESCRIPTION
**Pull request by mvm-sap**
For the full details of the change including screenshots see issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Screenshots ?

**Comment by vogella** [comment]
The sap specific styling should be done by a sap extension to the dark theme

IEclipsePreferences#org-eclipse-ui-workbench:com-sap-adt-tools-abapsource-ui {

**Comment by vogella** [comment]
Please adjust also the Linux dark theme

**Comment by mvm-sap** [comment]
Please find the screenshots in the issue link provided : https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

**Comment by thomasritter** [comment]
@vogella Adjusting the themes is very expensive. It took one person 3+ months to learn about how the themes work and get the Windows and Mac themes ready. Before we adjust the Linux theme we want to be sure that the Eclipse community approves the made changes and incorporate their feedback. Once Windows and Mac are finished we are fully committed to update the Linux theme.

**Comment by vogella** [comment]
Windows errors looks unrelated, merging

**Pull request merged**
