### PR TITLE
Adding the missing Notification snippets to the wiki

### PR DESCRIPTION
**Pull request by vogella**
Since a while we have three notification snippets but only on the documentation page.

### CODE REVIEW

**Comment by vogella** [comment]
I think @wimjongman requested that a long time ago....

**Review by BeckerWdf — APPROVED** [review]

**Comment by vogella** [comment]
The macs tests failures seems unrelated.

**Review by wimjongman — APPROVED** [review]
Thanks, Lars!

**Comment by vogella** [comment]
Mac failure is known: https://github.com/eclipse-platform/eclipse.platform.ui/issues/370

**Pull request merged**
