### PR TITLE
dummy change to check build

### PR DESCRIPTION
**Pull request by marcushoepfner**
check if build is successful

### CODE REVIEW

**Comment by marcushoepfner** [comment]
@laeubi pls. refer to the failures of this pr: https://github.com/eclipse-platform/eclipse.platform.ui/runs/12333575953
I did not change anything, just a assigned a statement to a variable.

Is this expected?

**Comment by laeubi** [comment]
It shows that some test fail on windows / macos, as previously these where not used as build verification it seems possible that no one noticed it before.

**Comment by marcushoepfner** [comment]
> It shows that some test fail on windows / macos, as previously these where not used as build verification it seems possible that no one noticed it before.

so we need to fix them? 
I cannot reproduce. I don't get these errors locally (in eclispe as pde test).

**Comment by iloveeclipse** [comment]
> so we need to fix them?

First, I would propose that we report them.
Depending on the problem nature, we can fix them or mute them or do whatever else needed to stop these actions to fail and confuse everyone.

**Comment by laeubi** [comment]
Of course its best to fix them as this obviously shows some problems (timings, os specific problems, ...) that can lead to random failures or undetected regressions...

**Comment by marcushoepfner** [comment]
Done! -> #665

**Pull request closed without merging**
