### PR TITLE
Adding Javadoc

### PR DESCRIPTION
**Pull request by Sorna-Sarathi**
Added the Javadoc for the cleanUp() in CocoaDarkThemeProcessor.

### CODE REVIEW

**Comment by elsazac** [comment]
To me, these failures seem to be infrastructure related- not related to the PR changes.

Are there known CI issues?

**Comment by merks** [comment]
@elsazac 

Yes, this looks unrelated to the PR itself.

@laeubi 

There is only this failure at the end:

image

I can't find anything earlier in the log with more clues...

**Comment by laeubi** [comment]
Looks like a bug in PDE API tools...

**Review by elsazac — APPROVED** [review]
This looks good to me

**Comment by elsazac** [comment]
Merging this as the test failures are unrelated to the changes.

**Comment by elsazac** [comment]
Given the current freeze period, I will merge these changes once the development cycle reopens, as the test failures are unrelated to the changes.

**Comment by mickaelistria** [comment]
As mentioned in the "RC1 reminder" mail, "Ongoing changes to documentation, tests or examples do not require approval.”

**Pull request merged**
