### PR TITLE
Remove blank Javadoc

### PR DESCRIPTION
**Pull request by jukzi**
This commit cleans up Javadoc that does not add information. It resolves ecj warnings:
 `Javadoc: Description expected after ...`
It helps to prevent future empty javadoc by disabling missingJavaDoc warnings. This resolves
 `Javadoc: Missing ...`

The modification is a result of regular expression search&replace:

in files `*.java`
 `^[\s]*\*[\s]*(@return|@param[\s]*[^\s]+|@throws[\s]*[^\s]+)\R([\s]*\*[\s]*@|[\s]*\*/\R)`
 ->`$2`
 `^([\s]*\*[\s]*\R)([\s]*\*/\R)`
 ->`$2`
 `^[\S\t ]*/\*\*\R[\s]*\*/\R`
 ->``

in files `org.eclipse.jdt.core.prefs`
 `org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc(Comments|Tags)\=[^\s]*`
 ->`org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc$1\=ignore`

### CODE REVIEW

**Comment by vogella** [comment]
Reminder: we are in release freeze period

**Comment by vogella** [comment]
I suggest to wait with this merge for the next 4.31 release, too many changes for the end game of a release.

**Comment by jukzi** [comment]
> I suggest to wait with this merge for the next 4.31 release, too many changes for the end game of a release.

I got that, but it's fair to work on it, or?

**Comment by jukzi** [comment]
ci failed with `Java heap space `

**Comment by jukzi** [comment]
@iloveeclipse jenkins keeps failing with `Java heap space` can you increase heap?

**Comment by jukzi** [comment]
```
5:59:43.020 [INFO] Resolve API baseline for org.eclipse.platform:org.eclipse.e4.tools:eclipse-plugin:4.10.300-SNAPSHOT
Exception in thread "Java indexing" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:230)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:200)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:686)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:91)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:675)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtIndexer.visitFile(AddJrtToIndex.java:146)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex$JrtTraverser.visitFile(AddJrtToIndex.java:1)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:751)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem$2.visitFile(JRTUtil.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.walkModuleImage(JRTUtil.java:720)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:244)
	at org.eclipse.jdt.internal.core.search.indexing.AddJrtToIndex.execute(AddJrtToIndex.java:275)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:542)
	at org.eclipse.jdt.internal.core.search.processing.JobManager$$Lambda$13342/0x00007ff902661710.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by iloveeclipse** [comment]
> @iloveeclipse jenkins keeps failing with `Java heap space` can you increase heap?

See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1342

**Comment by iloveeclipse** [comment]
> > @iloveeclipse jenkins keeps failing with `Java heap space` can you increase heap?
> 
> See #1342

However @akurtakov had a good argument not to merge #1342.

Can you please split this PR in smaller chunks, so not entire repo need to be rebuilt?

**Comment by laeubi** [comment]
I have now enabled tycho-4.0.5-SNAPSHOT for the build, this maybe can help with OOM as it contains a workaround for the problem, as far as I know JDT indexing can't be disabled...

**Comment by jukzi** [comment]
> I have now enabled tycho-4.0.5-SNAPSHOT for the build, this maybe can help with OOM as it contains a workaround for the problem, as far as I know JDT indexing can't be disabled...

still fails with oome

**Comment by laeubi** [comment]
I now replayed the build with suggested config from
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1343

lets see what happens...

**Comment by laeubi** [comment]
I need to further analyze that, it would be good to have a way to disable java indexing so we can get this one out of the way:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1650

**Comment by jukzi** [comment]
> Can you please split this PR in smaller chunks, so not entire repo need to be rebuilt?

done

**Pull request closed without merging**
