### PR TITLE
Adapt close-hovering icon for notification API

### LINKED ISSUE #2043: Notification-Overlay: old x-icon is shown when I hover over the new x
The new icon looks very good, but on hover, it becomes the old icon

grafik

### PR DESCRIPTION
**Pull request by HeikoKlare**
The close icon for showing notifications has been adapted with a more modern look and feel. The "active" version of the icon, used when hovering over it, is currently still the old one and does not fit the new icon anymore.

This change introduces a new "active" version of the notification close icon, being a thicker version of the non-active one.

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2043

### How it looks like
notification_close_active_new

### PR for images repo
Here is the according PR for the images repo: https://github.com/eclipse-platform/eclipse.platform.images/pull/82

### CODE REVIEW

**Comment by HeikoKlare** [comment]
@vogella @BeckerWdf may I ask you for feedback on this? Do you consider this is proper and intuitive way of providing hovering feedback (in the context of such a popup)?

**Review by BeckerWdf — APPROVED** [review]

**Comment by BeckerWdf** [comment]
> @vogella @BeckerWdf may I ask you for feedback on this? Do you consider this is proper and intuitive way of providing hovering feedback (in the context of such a popup)?

I like it!! 👍

**Comment by vogella** [comment]
Perfect, thanks for this.

**Comment by HeikoKlare** [comment]
Thanks for your feedback! Then I'll merge this together with the images repo PR https://github.com/eclipse-platform/eclipse.platform.images/pull/82

Since it's only an icon exchange, I do not rebase on master and trigger an unnecessary build before merging.

**Comment by vogella** [comment]
Thanks @HeikoKlare re for this work (including providing the icon). I hope that we will see the notification API used more often in the future. For example, the restart dialog after an installation operation might be  a good candidate for non-blocking notification.

**Pull request merged**
