### PR TITLE
Increase Version Number to accomodate #1132

### PR DESCRIPTION
**Pull request by Wittmaxi**
As discussed in #1132

### CODE REVIEW

**Comment by Wittmaxi** [comment]
@vogella

**Comment by vogella** [comment]
I think you plan to keep the API stable? So only increase the minor segment by 100

**Comment by vogella** [comment]
3.17.200 -> 3.17.300

**Comment by Wittmaxi** [comment]
Yes, you are absolutely right, the API should stay stable. I have updated my PR :) @vogella

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
This PR is not needed, version was already bumped for 4.30 via 324229d513c8735524422904c659d8b1404183bb

**Comment by vogella** [comment]
@Wittmaxi so the build failure of https://github.com/eclipse-platform/eclipse.platform.ui/pull/1132 is not related to missing version increase?

**Comment by HeikoKlare** [comment]
I think the build there is failing, because the `FindAndReplace` class is currently marked `public`, which would be a public API change. Reducing its visibility will resolve the version problem.

**Pull request closed without merging**
