### PR TITLE
Replace custom OverlayIcon classes with Jface' DecorationOverlayIcon

### PR DESCRIPTION
**Pull request by HannesWell**

### CODE REVIEW

**Comment by BeckerWdf** [comment]
@HannesWell:
Can I support you with manual testing on this topic?

**Comment by HannesWell** [comment]
> @HannesWell:
> Can I support you with manual testing on this topic?

Yes. I tested it locally on my Windows computer and AFAICT it worked well, but a second look would be good, maybe on another Plattform.

Two of the changed places are relativly easy to Test, you just need a Project with a nature in your workspace respectivly have to Open the new folder Wizard and unfold the 'Advanced' section.

The third one was a bit more difficult, at least for me only using the SDK workspace.
I had to modify the only extension in the `o.e.sdk` plugin.xml referencing `ActivityCategoryPreferencePage` to have the 'allowAdvanced' property set to false. Furthermore I had to uncomment the `isLocked` check and then eventually could trigger the code-path when searching for 'Capabilities' in the preferences of a launched Eclipse.

**Comment by BeckerWdf** [comment]
> > @HannesWell:
> > Can I support you with manual testing on this topic?
> 
> Yes. I tested it locally on my Windows computer and AFAICT it worked well, but a second look would be good, maybe on another Plattform.
> 
> Two of the changed places are relativly easy to Test, you just need a Project with a nature in your workspace respectivly have to Open the new folder Wizard and unfold the 'Advanced' section.

So you mean this one:
image


> The third one was a bit more difficult, at least for me only using the SDK workspace. I had to modify the only extension in the `o.e.sdk` plugin.xml referencing `ActivityCategoryPreferencePage` to have the 'allowAdvanced' property set to false. Furthermore I had to uncomment the `isLocked` check and then eventually could trigger the code-path when searching for 'Capabilities' in the preferences of a launched Eclipse.

I didn't get this. Where on the UI do see these icons?

**Comment by HannesWell** [comment]
> So you mean this one:

Yes exactly, that looks good already. :)



> > The third one was a bit more difficult, at least for me only using the SDK workspace. I had to modify the only extension in the `o.e.sdk` plugin.xml referencing `ActivityCategoryPreferencePage` to have the 'allowAdvanced' property set to false. Furthermore I had to uncomment the `isLocked` check and then eventually could trigger the code-path when searching for 'Capabilities' in the preferences of a launched Eclipse.
> 
> I didn't get this. Where on the UI do see these icons?

In a development workspace where you have `org.eclipse.sdk` checkout from the `eclipse.platform` repository as well as `ActivityCategoryPreferencePage` from `eclipse.platform.ui`, you have to change the `plugin.xml` at the marked location and have to comment out `isLocked(category)` in `ActivityCategoryPreferencePage.getColumnImage()`:

grafik

From that workspace you launch another Eclipse and in its preferences search for `Capabilities` and the icons with an overlayed lock should be displayed: 
grafik

**Comment by BeckerWdf** [comment]
> > So you mean this one:
> 
> Yes exactly, that looks good already. :)

That's the current / old version still.

**Comment by HannesWell** [comment]
> > > So you mean this one:
> > 
> > 
> > Yes exactly, that looks good already. :)
> 
> That's the current / old version still.

I'm not sure if there is a misunderstanding. The intention of the PR is not to change the resulting icons at all, they should stay as they are. It should just save unnecessary code.

@BeckerWdf do you want to test this before it is merged or with an I-builds afterwards?
Because for me this is ready, I'm just waiting for your results. :)

**Comment by BeckerWdf** [comment]
> > > > So you mean this one:
> > > 
> > > 
> > > Yes exactly, that looks good already. :)
> > 
> > 
> > That's the current / old version still.
> 
> I'm not sure if there is a misunderstanding. The intention of the PR is not to change the resulting icons at all, they should stay as they are. It should just save unnecessary code.

I know.

 
> @BeckerWdf do you want to test this before it is merged or with an I-builds afterwards? Because for me this is ready, I'm just waiting for your results. :)

I will try to test today.

**Comment by BeckerWdf** [comment]
I manually tested as described above. All looks good (same as before).

**Review by BeckerWdf — APPROVED** [review]
manual test on macOS OK

**Comment by HannesWell** [comment]
@BeckerWdf thanks for your help testing this.

**Pull request merged**
