### PR TITLE
Improve problem filter scope wording

### PR DESCRIPTION
**Pull request by Bananeweizen**
* use "selected elements" instead of "selected element" in all implementations
* use "their children" due to the plural form of "elements"
* remove double blank in working set related scope

### CODE REVIEW

**Review by BeckerWdf — APPROVED** [review]

**Comment by BeckerWdf** [comment]
Good catch!

**Comment by mickaelistria** [comment]
Changes in documentation are OK even in RC, let's merge it now.

**Comment by BeckerWdf** [comment]
are "[messages.properties](https://github.com/eclipse-platform/eclipse.platform.ui/pull/989/files#diff-1025ba66a3f389cd3073ef5bdec0d099e8a899a0d4dc9398c830c76005d0d760)" changes really "documentation"?

**Comment by mickaelistria** [comment]
Not really, indeed.
However, I think it's OK to apply the rule for typos is labels as well. It's not a regression fix, but it's surely not a risky change either.

**Comment by vogella** [comment]
Agreed, label fixes are fine even in rc1 or rc2. The rules are to help us
deliver good software not to prevent us from doing this

Mickael Istria ***@***.***> schrieb am Fr., 25. Aug. 2023,
16:01:

**Pull request merged**
