### PR TITLE
Amendment to pull-request #193

### PR DESCRIPTION
**Pull request by ghost**
viewRegistry.find(elementId) only returns null for views, which have been disabled by an expression-based activity.
For other mechanisms, WorkbenchActivityHelper.filterItem(view) has to be used.

### CODE REVIEW

**Comment by ghost** [comment]
See [here](https://github.com/eclipse-platform/eclipse.platform.ui/commit/5cbd0ba5df4f211d3f0785e1dd22b14b5546cf6b#commitcomment-85141792) for a more detailed discussion.

**Comment by mickaelistria** [comment]
Can you please amend the commit so it has a self explanatory title?
Reference to former commits is more suitable in the commit message

**Comment by merks** [comment]
@dogla Thanks for testing, reporting and providing a test case. 

@pzi-dsa Thanks for fixing so quickly in time for M1. 

@mickaelistria  It would be good to merge this for M1 because it’s a regression right?

**Comment by mickaelistria** [comment]
@merks yes, we can/should merge it as soon as builds are successful; the check-freeze can be ignored today, it's pretty conservative and bugfixes are still welcome. If you have the opportunity to merge before me, feel free.

**Review by mickaelistria — APPROVED** [review]

**Comment by mickaelistria** [comment]
Thank you!

**Pull request merged**
