### PR TITLE
Enable org.eclipse.ui.tests.rcp in Tycho build

### PR DESCRIPTION
**Pull request by HeikoKlare**
See https://github.com/eclipse-platform/eclipse.platform.ui/discussions/1143

### CODE REVIEW

**Comment by HeikoKlare** [comment]
Failing test is documented in #370.

Any objections on merging this test (re-)activation?

**Comment by iloveeclipse** [comment]
> Any objections on merging this test (re-)activation?

The only one objection I see is that after merging so many repos into platform.ui the test times increased a lot, jenkins needs now nearly a hour to complete. Would be nice if someone could split test execution on jenkins based on changed code. 

I believe that was proposed on one of the "merge git repo" actions.

**Comment by HeikoKlare** [comment]
I see you point. Splitting up test execution absolutely makes sense. Even for the GH actions builds, it could make sense to have different jobs for subsets of the test projects to reduce the time for getting feedback when submitting a PR. Seems to be a important topic to me, but should be considered independent from this PR.

Concerning the tests enabled by this PR: they add some few seconds (less than 10) to test execution time. At the same time, they seem to be the only tests that actually test some startup/shutdown behavior of the workbench (correct me if I'm wrong), so it's well invested time (from my point of view). Also note that this PR only enables the tests in the Tycho build executed by GH actions. I did not find information in the Jenkins logs that the test bundle is considered in those builds at all, so I think this PR will not affect the Jenkins builds.

**Comment by akurtakov** [comment]
FWIW, only 1 repo (platform.text) was merged into platform.ui the rest were merged into platform one.

**Comment by HeikoKlare** [comment]
> FWIW, only 1 repo (platform.text) was merged into platform.ui the rest were merged into platform one.

True. If I'm not mistaken, that merge by itself doubled the build time (from ~30 minutes to ~1 hour).

I hope you also see the general build time topic as something to be addressed independent from this PR and that it should not prevent this test reactivation to be performed.

**Comment by akurtakov** [comment]
For the sake of having correct data:
* 4.28 (aka prior merge) - 36 mins (https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/R4_28_maintenance/)
* 4.29 (aka after the merge) - 45 mins (https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/R4_29_maintenance/)

So slow down is 9 mins there must be other things slowing down the build. 
Most likely build time depends on load of the CI servers - as per https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/ build time ranges from 41 to 56 mins.

**Comment by akurtakov** [comment]
I've rebased the patch on master so there is another build to compare with the first one (56 mins). There will most likely be multi minute difference just proving your point that speeding up the build is not an issue here.

**Comment by HeikoKlare** [comment]
Yes, build times vary a lot. I just considered the times the whole GitHub actions CI check took [right before the merge](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5370682845) and [right after the merge](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5399689866). But actually it does not really matter what the reason for the build times is and what effect the merge had, as no one wanted to challenge the decision for performing the merge :-)

Build times added through test activation in this PR can also be seen in the logs. E.g., the Tycho build in the GH actions run on Windows took around 12 seconds in its last execution, see https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/6259047161/job/16994277236#step:7:20179.

**Comment by akurtakov** [comment]
Next build took 49 mins on Jenkins (https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-1148/2/).

**Comment by akurtakov** [comment]
Merging.

**Comment by HeikoKlare** [comment]
Thanks @akurtakov!

**Comment by laeubi** [comment]
Just to clarify here about the varying build times, actually it is not only the test-execution/compilation itself, it is also API analysis that takes a considerable amount of time, some bundles require **minutes** to complete because they have large dependency chains and currently API tools recompile them to perform the analysis and in general is quite slow.

There is already a switch to skip API analysis if the bundle itself was replaced by the baseline, so if there is no change in the bundles this is skipped and save us some time, but I don't think this will work smoothly for test as it will require a deep analysis of the dependencies and likely will always return true as we have only some very big test bundles instead of small module local ones, given the tight interaction of platform code, literally **any** change can break anything.

Next there are several issues I created that currently seem to hinder us using parallel execution (and therefore maybe use more CPUs) but the conclusion was more "it's impossible" or "to risky":

- https://github.com/eclipse-platform/eclipse.platform.ui/issues/921
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/920
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/919
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/918

so at the moment I do not see much room for improvement without major effort what might outweigh some additional minutes to wait for the verification build.

**Comment by laeubi** [comment]
I have now created a profiler PR here:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1153

**Pull request merged**
