### PR TITLE
Import archive project with exclude all resource filter #748

### LINKED ISSUE #748: Importing existing archive projects into the workspace using Standard workbench wizard doesn't instantiate the ResourceFilter's that are stored in the project description
**Issue is reproducible in latest nightly build** i.e. 
https://download.eclipse.org/eclipse/downloads/drops4/I20230507-1800/eclipse-SDK-I20230507-1800-win32-x86_64.zip

and respective **bugzilla issue is [here]**(https://bugs.eclipse.org/bugs/show_bug.cgi?id=553246).

**Issue Description copied from Bugzilla:**

The minimal example in the form of an archive Java project.

**Found in:**
Eclipse Oxygen (4.7) to Eclipse 2019-09 R.

**Steps to create an archive project:**
1. Create a new java project as "JavaExampleProject". use File > New > JavaProject
2. Create the folder with the name "res" under the java project "JavaExampleProject". RightClick on the project and select New > Folder 
3. RightClick on the project "JavaExampleProject" and select Properties. The Properties of the "JavaExampleProject" will be populated.
4. Properties for JavaExampleProject dialog will be populated to select the node "Resource Filters". use Resource > Resource Filters
5. The Resource Filters page will be viewed. 
6. Select the Add Filter button. FilterEditDialog will be populated.
7. In the FilterEdit dialog, the following things need to be selected
7a. Select Exclude all Radio in the "Filter type" group. 
7b. Select Folders Radio in the "Applies to" group.
7c. In the File and Folder Attributes group Select "Name" value in the first combo and "matches" value in the second combo and enter the value "res" 
7d. Select Ok button
8. Make sure that under Resource Filters page node Exclude All: should contain the child node "Name matched res"
9. Select Apply and close in the Properties dialog.

**Steps to Archive project.**
1. Go to the File directory where the project is placed.
2. Use any of the file archiver utility available for Windows such as 7-Zip or WinRAR
3. archive the project.

**Steps to reproduce:**
1. Use File > Import and then invoke "Existing project into workspace" 
2. In the Standard workbench wizard select projectFromArchiveRadio button.
3. Select the archive project "JavaExampleProject" file that was archive from the file system and perform finish

**Observed behavior:**
The Imported archive project will include all the ResourceFilter's file system objects[Folder/Files] stored in the project description.
i.e after importing "JavaExampleProject" the "res" folder will also be imported to the workbench.

**Expected behavior:**
The Imported archive project should not include ResourceFilter's file system objects[Folder/Files] stored in the project description.
i.e after importing "JavaExampleProject" the "res" folder should not be imported to the workbench.

**Root Cause**

I was able to analyze and track down the problem as follows:

The org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage.createExistingProject() builds up to create a project structure which internally calls
org.eclipse.ui.wizards.datatransfer.ImportOperation.execute() in which it calls org.eclipse.ui.dialogs.ContainerGenerator.generateContainer which calls 
org.eclipse.ui.dialogs.ContainerGenerator.createProject() 

Once the project is created the project is opened with constant IResource.NONE which makes the project to refresh. On refresh operation, the resource filters configure which files and folders are included automatically in a project resource hierarchy.
But the problem is when the refresh operation is performed not all the specified file system objects would have Imported into the workspace which causes the refresh operation to assume none of the files and/or folders that match the filter condition exits.

**Proposed solution:**
Instead of projectHandle.open(subMonitor.split(1) in the org.eclipse.ui.dialogs.ContainerGenerator.createProject() make the project to refresh in the background by setting
projectHandle.open(IResource.BACKGROUND_REFRESH, subMonitor.split(1)) which makes the project to refresh only after all the specified file system objects would have Imported into the workspace

Example project used to reproduce the issue is attached below
[JavaExampleProject.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/11430340/JavaExampleProject.zip)

### PR DESCRIPTION
**Pull request by lathapatil**
Background refresh fix for archive project import with exclude all resource filter

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/748

### CODE REVIEW

**Comment by elsazac** [comment]
this can have some reviews

**Comment by merks** [comment]
Sorry,  should have done a rebase.  :-(

**Comment by merks** [comment]
@lathapatil 

One of the failures here is for the mac for the new test being added here:
```
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at junit.framework.Assert.assertFalse(Assert.java:47)
	at junit.framework.TestCase.assertFalse(TestCase.java:216)
	at org.eclipse.ui.tests.datatransfer.ImportExistingArchiveProjectFilterTest.processElementAndChildren(ImportExistingArchiveProjectFilterTest.java:147)
	at org.eclipse.ui.tests.datatransfer.ImportExistingArchiveProjectFilterTest.processElementAndChildren(ImportExistingArchiveProjectFilterTest.java:151)
	at org.eclipse.ui.tests.datatransfer.ImportExistingArchiveProjectFilterTest.testFolderVisibilityPostZipProjectImport(ImportExistingArchiveProjectFilterTest.java:136)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:140)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication$1.run(AbstractUITestApplication.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1152)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1043)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:34)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:129)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
----- testFolderVisibilityPostZipProjectImport
testFolderVisibilityPostZipProjectImport: setUp...
testFolderVisibilityPostZipProjectImport: tearDown...
```

I wonder if refresh in a background could result in errors that depend on the timing/scheduling of that background job?   I.e., it might or might not complete very quickly.   I wonder if it isn't more proper to ensure that the project is created initially with the proper description?

**Comment by lathapatil** [comment]
@merks Looks like its not failing in the last run or am I missing something to notice here ?

**Comment by merks** [comment]
I tested in the debugger when the refresh of the project happens and indeed it's blocked until the import operation as a whole completes, so this looks safe.

**Comment by merks** [comment]
@lathapatil 

It turns out that there is a timing issue.  If the test's verification runs before the scheduled refresh operation completes, the test will fail.   It makes me wonder if a better fix would not have been to add an explicit refresh after the files are imported...

**Comment by lathapatil** [comment]
> @lathapatil
> 
> It turns out that there is a timing issue. If the test's verification runs before the scheduled refresh operation completes, the test will fail. It makes me wonder if a better fix would not have been to add an explicit refresh after the files are imported...

If it is the only issue with sporadic testcase failure .. will it resolve by adding sleep time before test's assertion ?

**Pull request merged**
