### PR TITLE
Bug-563090: improve dark theme look of restore icon

### PR DESCRIPTION
**Pull request by betamaxbandit**
The icon contrast of the restore button, of minimized views, has been improved so it looks acceptable in light and dark theme.

Original bugzilla:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563090

### CODE REVIEW

**Comment by betamaxbandit** [comment]
I have changed the brightness of the icon so it looks better in dark theme. The difference is quite subtle. It's a balancing act so it still looks ok in light theme.

Screenshot before and after:
restore button - dark theme- before

restore button - dark theme- after

restore button - light theme - before

restore button - light theme - after

**Comment by betamaxbandit** [comment]
The restore button is treated differently depending on where it is drawn. In the screenshot below, the button highlighted in red is drawn by the CTabFolder and the buttons highlighted in green are drawn by TrimStack.

restore button - annotated

For the CTabFolder case the button is drawn on the GC using the parent's foreground colour. I think that's why it looks sharp and bright irrespective of dark or light theme.
org.eclipse.swt.custom.CTabFolder.setMaximized(boolean)
  org.eclipse.swt.custom.CTabFolder.createButtonImage(Display, int)
    org.eclipse.swt.custom.CTabFolderRenderer.draw(int, int, Rectangle, GC)
      org.eclipse.swt.custom.CTabFolderRenderer.drawMaximize(GC, Rectangle, int)

For the TrimStack case the button has a discreet icon image (RESTORE_ICON_URI) associated with it which is used verbatim.
org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.createWidget(Composite, MToolControl, CSSRenderingUtils)

The buttons look different, but personally I think this looks ok; the red highlighted button is brighter which could be taken to indicate the view is maximised; the green highlighted buttons are less emphasised indicating minimised.
However there is a comment in the original bugzilla which suggests the CTabFolder buttons should be replaced with discreet icons. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563090#c5
Please let me know if I have understood correctly and if you think this change is still necessary,

**Comment by vogella** [comment]
@betamaxbandit can you also update the svg in the eclipse.platform.images repo?

**Comment by vogella** [comment]
Thanks @betamaxbandit look good to me.

If you find the time, please also update the svg in the eclipse.platform.images repo

**Comment by betamaxbandit** [comment]
> 

Hi @vogella , Thanks. OK will do.

**Comment by betamaxbandit** [comment]
> > 
> 
> Hi @vogella , Thanks. OK will do.

Hi @vogella , I've updated the svg with this PR:
https://github.com/eclipse-platform/eclipse.platform.images/pull/6
Regards John

**Pull request merged**
