### PR TITLE
[test] delete ControlObservableValueTest.png after test

### PR DESCRIPTION
**Pull request by jukzi**
2MB artifact in i builds

### CODE REVIEW

**Comment by jukzi** [comment]
@HeikoKlare what is that png for? it is saved in ever build. for example
https://download.eclipse.org/eclipse/downloads/drops4/I20240916-1800/testresults/ep434I-unit-mac64-java17_macosx.cocoa.x86_64_17/org.eclipse.jface.tests.internal.databinding.swt.ControlObservableValueTest.ControlObservableValueTest.png

**Comment by akurtakov** [comment]
Screenshots like this are generally a "debugging" tool when trying to fix UI test. If they are deleted like that they can not be inspected so it's probably better to not generate them at all.

**Comment by jukzi** [comment]
If the test fails the screenshots remain as artifact. That could be useful. Maybe better they would only be generated on fail?

**Comment by akurtakov** [comment]
> If the test fails the screenshots remain as artifact. That could be useful. Maybe better they would only be generated on fail?

If you manage to do that it would be awecome.

**Comment by jukzi** [comment]
ignoring unrelated `Download of osgi.bundle,org.eclipse.jface.examples.databinding,1.4.400.v20240424-0956 failed` on linux

**Comment by HeikoKlare** [comment]
> what is that png for? it is saved in ever build. for example

> Screenshots like this are generally a "debugging" tool when trying to fix UI test.

The places where screenshots are saved that I have seen so far are for documenting and debugging inproper focus handling, like here:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/be54f35f78bf182dad6b3d4beefc9d7f0d209068/tests/org.eclipse.ui.workbench.texteditor.tests/src/org/eclipse/ui/internal/findandreplace/FindReplaceUITest.java#L84-L87

So your fix to only save the screenshot in case the failure that needs to be analyzed via that screenshot occurs is the right thing to do.

**Pull request merged**
