### PR TITLE
Added Javadoc 

### PR DESCRIPTION
**Pull request by Bharath-2003**
Added the java documentation for a missing one.

### CODE REVIEW

**Comment by elsazac** [comment]
To me, these failures seem to be infrastructure related- not related to the PR changes.

Are there known CI issues?

**Comment by merks** [comment]
This one has some test failures but that doesn't look related to the changes.   I'm not sure those failures are recorded as issues anywhere yet.

**Review by elsazac — APPROVED** [review]
Looks good to me

**Comment by elsazac** [comment]
Given the current freeze period, I will merge these changes once the development cycle reopens, as the test failures are unrelated to the changes.

**Comment by mickaelistria** [comment]
> Given the current freeze period, I will merge these changes once the development cycle reopens, as the test failures are unrelated to the changes.

As mentioned in the "RC1 reminder" mail, "Ongoing changes to documentation, tests or examples do not require approval.”

**Pull request merged**
