### PR TITLE
Make use of Java 17 features in o.e.ui.tests

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Alex, I see you extensively uses improved instanceof. Nothing against it, but we've patched compiler code recently to generate a bit different bytecode for that (https://github.com/eclipse-jdt/eclipse.jdt.core/issues/585), and I wonder if we could first make sure the IBuilds use updated ECJ version?

**Comment by akurtakov** [comment]
I'm on it.

**Comment by akurtakov** [comment]
Thanv you @vogella for starting with these tests move to Java 17 so we can identify and test more such things this cycle.

**Comment by akurtakov** [comment]
ECJ has been updated so this is fine to go.

**Pull request merged**
