### PR TITLE
Find/replace overlay: allow pasting into replace input field #2509

### PR DESCRIPTION
**Pull request by HeikoKlare**
While actions of the target editor are properly deactivated when the find input field of the FindReplaceOverlay has focus, the same does not happen for the replace input field. In consequence, for example, you cannot paste clipboard content into the replace input field via the according keyboard shortcut (CTRL+V).

With this change, the functionality to deactivate target editor actions is also applied when the the replace input field has focus, in addition to the find input field.

Contributes to https://github.com/eclipse-platform/eclipse.platform.ui/issues/2509

### Demo
Behavior before fix:
findreplace_insert_replace_before

Behavior after fix:
findreplace_insert_replace_after

### CODE REVIEW

**Comment by BeckerWdf** [comment]
> Contributes to #2509

This reported issue from #2509 still exists with this PR.

**Comment by HeikoKlare** [comment]
> > Contributes to #2509
> 
> This reported issue from #2509 still exists with this PR.

This PR does not completely fix #2509. It just fixes pasting into the replace field for non-multipage-editors (for which I added an additional comment to #2509). Probably I should have opened a separate issue for that, but I first though they are highly related, as they are all about pasting into the overlay (and using other shortcuts).

**Comment by HeikoKlare** [comment]
In my opinion, this should be fixed for the upcoming release, as it is quite annoying to not be able to use common shortcuts to cut, copy, paste etc. in the replace input field of the find/replace overlay.

@akurtakov @vogella may I ask for the PMC approval of one of you (or any other PMC member) to still merge this?

**Comment by akurtakov** [comment]
I haven't reviewed the actual code change nor tested it but the issue looks important enough to worth PMC +1 from me for RC1.

**Comment by akurtakov** [comment]
Code change looks good. Please push when verifications succeed.

**Comment by HeikoKlare** [comment]
Thank you!

**Pull request merged**
