### PR TITLE
Improvement to Light and Dark theme for Linux

### PR DESCRIPTION
**Pull request by mvm-sap**
Existing Light and Dark Theme has been updated for Linux. More details could be found in issue : https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114
Will update with screenshots asap.
Meanwhile, would request to get feedback from Linux Community for this new change in theme.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
> Meanwhile, would request to get feedback from Linux Community for this new change in theme.

Germans have a nice word "Pixelbrei", that describes how it looks on Linux now. I don't see any border anywhere, every title of every view tab seem to be drawn randomly on screen, everything is grayish, no contrast. Note wrong background for toolbar items in Staging view too.

image

Beside this, hovered non-active editor tab is painted in black color:

image

Here how it looks like **without** themes and it is much easier to read for my eyes:

image

**Comment by vogella** [comment]
@iloveeclipse did you restart after activating theme / setting the theme? This is required to trigger some OS styling functions.

For me the new light theme looks good:

image

The color for the selected tab in the new dark theme seem off with its blue text color.

image

**Comment by iloveeclipse** [comment]
> did you restart after activating theme / setting the theme?

Of course.

> For me the new light theme looks good

Try to open more as one view per stack.

**Comment by vogella** [comment]
> Try to open more as one view per stack.

OK, I can now confirm that this change  make the theme look bad:

image

**Comment by mvm-sap** [comment]
I tested the changes on a Windows machine, just by removing the OS dependency in plugin.xml . Need some time to set up the same environment in Ubuntu. Shall do it and try to fix these issues.

**Comment by mvm-sap** [comment]
Hover_Unselected_TabLinux

Hover on the unselected tab (Declaration tab next to Javadoc) in views display darker grey in Ubuntu. And, I'm looking into the issue reported with respect to border of the selected tab in views.

**Comment by mvm-sap** [comment]
Screenshot from 2024-07-30 15-59-51


Text Color of the selected tab in dark theme as well looks correct. This screenshot is taken from Ubuntu.

**Comment by thomasritter** [comment]
@vogella Thanks for pointing out the "Types" view. The background needs to be gray. I added the issue to the umbrella issue #2114.

**Comment by vogella** [comment]
Looking better for me: 

image


image

**Comment by vogella** [comment]
@mvm-sap this change seem to suffer from the same toolbar background color issue reported by @HannesWell in https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114#issuecomment-2241561690. 

image


Is this something your team is working on?

**Comment by vogella** [comment]
@HeikoKlare AFAIK you have Windows and Linux systems available. Could you give these themes a try and check if you see significant differences to the new themes on Win?

**Comment by mvm-sap** [comment]
@vogella  we are working on this issue https://github.com/eclipse-platform/eclipse.platform.ui/pull/2137#issuecomment-2259947533 .  it has affected all Mac, Linux and Windows. Will fix and update soon.

**Comment by HeikoKlare** [comment]
I have compared the themes on Windows and Linux side-by-side and did not find any differences, except for the ones that have existed before due to different OS behaviors (like highlight colors for tree selections). And, as expected, the glitches already documented for the Windows and MacOS themes are also present in the Linux theme, but in the context of this PR I would kind of "expect" that and have a consistent fix for all three themes afterwards.

I have taken quick example pictures for light and dark theme with two devices side-by-side, but I don't think they provide any real value. Comparing (existing) screenshots will probably be easier and more helpful. Still, here they are:
image
image

**Comment by BeckerWdf** [comment]
@HeikoKlare: So you would say this is good to be merged?

**Comment by HeikoKlare** [comment]
From what I have tested so far, I would say it is ready to be merged, yes. But note that I am not a daily Linux user and only use it for testing specific changes.
I am not sure whether the concerns of @iloveeclipse have all been addressed or discussed. Several points (like view tab header separation and faulty background colors of toolbar icons) have already been discussed for Windows and MacOS, proposals have been made and they will be addressed. But will that address the general "Pixelbrei" concern? Of course, this is also about individual preferences and about getting used to changes, so probably not everyone will agree with every decision. I just want to avoid that we merge a Linux theme change that will not be tested by the ones introducing and agreeing with the change but not using Linux on a daily basis, but will be tested by people that may not fully agree with the changes.
So I would prefer to have at least one approval for the change by a daily Linux user.

**Comment by BeckerWdf** [comment]
> So I would prefer to have at least one approval for the change by a daily Linux user.

I totally agree with you.

**Comment by iloveeclipse** [comment]
I honestly don't care anymore as long as there is an option to switch css off completely.
 
I see that the overall trend seem to remove every difference between active/not active tab, all colors are in same gray tone except editor, no separators nowhere, everything seem just "randomly" painted on screen. It might be there will be some improvements over the current PR state, but I've switched to default no-css theme for a long time and now after trying this PR I'm just being happy to not follow the trend and have a usable IDE independently what css changes are submitted.

So feel free to merge this if that should be the future Eclipse L&F on all platforms.

**Comment by mvm-sap** [comment]
Screenshot from 2024-08-01 17-17-27

Just did a small change with respect to selected tab outline. Haven't committed the changes yet, but would like to get your opinion on the same.

**Comment by iloveeclipse** [comment]
> Just did a small change with respect to selected tab outline

Not sure what outline mean, but if you mean selected tab has now border painted - it is better as before fore sure.

**Comment by mvm-sap** [comment]
> > Just did a small change with respect to selected tab outline
> 
> Not sure what outline mean, but if you mean selected tab has now border painted - it is better as before fore sure.

yes, border for selected tab in Views

**Comment by mvm-sap** [comment]
Will wait for some more feedback and then commit this change

**Comment by iloveeclipse** [comment]
@mvm-sap : please remove merge commits from PR.

**Comment by vogella** [comment]
@mvm-sap please squash everything into one commit and force push the update

**Comment by mvm-sap** [comment]
> Screenshot from 2024-08-01 17-17-27
> 
> Just did a small change with respect to selected tab outline. Haven't committed the changes yet, but would like to get your opinion on the same.

Now, border for the selected tab in view is also included in this commit

**Comment by mvm-sap** [comment]
> > Screenshot from 2024-08-01 17-17-27
> > Just did a small change with respect to selected tab outline. Haven't committed the changes yet, but would like to get your opinion on the same.
> 
> Now, border for the selected tab in view is also included in this commit

Same issue was found in Mac and Windows as well. It has been fixed with the PR - https://github.com/eclipse-platform/eclipse.platform.ui/pull/2150

**Comment by vogella** [comment]
Thanks @HeikoKlare for the comparison, lets merge this so that Mac, Win and Linux is in sync with its presentation

**Pull request merged**
