### PR TITLE
Remove the inner background from onboarding image

### LINKED ISSUE #695: Consider removing the inner background from image to make them less "strong" in the dark theme

### PR DESCRIPTION
**Pull request by BeckerWdf**
Fixes: https://github.com/eclipse-platform/eclipse.platform.ui/issues/695

### CODE REVIEW

**Comment by vogella** [comment]
@BeckerWdf thanks a bunch. Maybe the same is necessay for the JDT image?

**Comment by BeckerWdf** [comment]
> @BeckerWdf thanks a bunch. Maybe the same is necessay for the JDT image?

How do they look in dark on your side?

**Comment by vogella** [comment]
Awesome

image

image

**Comment by BeckerWdf** [comment]
How doe the JDT icons look on your side?

**Comment by laeubi** [comment]
> Awesome

I must confess I would expect more something like this:

grafik

also the icon now lost its nice looking lighting effect...

**Comment by BeckerWdf** [comment]
> I must confess I would expect more something like this:

ah sure. You are right....

**Comment by BeckerWdf** [comment]
@laeubi: See https://github.com/eclipse-platform/eclipse.platform.ui/pull/699

**Pull request merged**
