### PR TITLE
ImportExistingProjectsWizardTest: fix leaked Shells #2379

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2379

### CODE REVIEW

**Comment by jukzi** [comment]
Hello mergebot wakeup - build failed - @HannesWell 
`[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.9:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.ui.tests.harness: Only qualifier changed for (org.eclipse.ui.tests.harness/1.10.400.v20241010-1151). Expected to have bigger x.y.z than what is available in baseline (1.10.400.v20240321-1245) -> [Help 1]`

**Comment by jukzi** [comment]
> (org.eclipse.ui.tests.harness/1.10.400.v20241010-1151). Expected to have bigger x.y.z

That was bumped yesterday. rebasing this commit fixed the error.

**Comment by jukzi** [comment]
ignoring random failing testItemOrder https://github.com/eclipse-platform/eclipse.platform.ui/issues/195

**Comment by HannesWell** [comment]
> > (org.eclipse.ui.tests.harness/1.10.400.v20241010-1151). Expected to have bigger x.y.z
> 
> That was bumped yesterday. rebasing this commit fixed the error.
> 

Maybe the concurrent bump caused some inconsistent results here, but that's just a guess.

**Pull request merged**
