### PR TITLE
Using Text blocks in ui.tests by moving to Java 17

### PR DESCRIPTION
**Pull request by akurtakov**
As the whole infrastructure has been moved to Java 17, we can also update our tests to use Java 17.

### CODE REVIEW

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/521 continued to have less awkward symbols in text blocks.

**Comment by akurtakov** [comment]
Abandon as the other patch was merged.

**Comment by iloveeclipse** [comment]
Sorry, I thought they were different. What was the reason for this one?

**Comment by akurtakov** [comment]
NP, I was just trying to reduce some '\' symbols in the textblock. Nothing important, more about me testing the extend of text blocks.

**Comment by trancexpress** [comment]
Isn't this PR "better"? Since there are fewer unexpected symbols. (comparing to https://github.com/eclipse-platform/eclipse.platform.ui/pull/521/files)

Or the change here doesn't work and the extra symbols are needed?

**Comment by akurtakov** [comment]
I don't think they are needed but also they are not hurting so no time to rebase it. Even with the first patch it's better than it used to be.

**Pull request closed without merging**
