### PR TITLE
Use utf-8 encoding in StatusDialogTest

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by vrubezhny** [comment]
So, it's the same as the first one (in #575). Looking at the raw file and its encoding - it works. The problem is in Github diff view UI.

**Comment by akurtakov** [comment]
Sounds like it

**Comment by akurtakov** [comment]
I'll merge this one so we can see whether it's only the diff view showing problem.

**Comment by akurtakov** [comment]
So it looks fine here https://github.com/eclipse-platform/eclipse.platform.ui/commit/ec9f76920367a75451d99cafedc5f032c46467f9 aka it's github bug we have been facing

**Pull request merged**
