### PR TITLE
Enable maven profiler to see what adds to the build times

### PR DESCRIPTION
**Pull request by laeubi**
This add the maven profiler and enables to output the results to the console.

This is not really meant to be merged, just to see what currently takes the most time when building a PR.

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov looking at the profiling results, the javadoc generation takes considerable time. I can try to skip this for plugins that have not changed but of course then we only get new issues reported (not existing ones).

**Comment by akurtakov** [comment]
Please no. There are enough times javadoc bites us to want it to be in better shape.

**Comment by akurtakov** [comment]
I think this draft can be closed now, no?

**Comment by laeubi** [comment]
It depends it can still be used to see what is taking most of the time, I'll rebase to get a new measure now.

**Pull request closed without merging**
