### PR TITLE
PropertyPageNode: log full exception if any instead of popup only

### PR DESCRIPTION
**Pull request by jukzi**
This issue did not show the root exception:
https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/570

### CODE REVIEW

**Comment by jukzi** [comment]
@SougandhS this should help to get better exceptions in your case.

**Comment by SougandhS** [comment]
> @SougandhS this should help to get better exceptions in your case.

Yess 👍

**Comment by jukzi** [comment]
With this PR:
image

**Comment by jukzi** [comment]
Random build failures are known:
https://github.com/eclipse-platform/eclipse.platform.ui/issues/926
https://github.com/eclipse-platform/eclipse.platform.ui/issues/370

**Pull request merged**
