### PR TITLE
Add extension point for generic editor content assistant look and feel.

### PR DESCRIPTION
**Pull request by andrewL-avlq**
Adds an extension point so that the look and feel of the generic editor content assistant can be configured by extension contribution.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please elaborate about the use case that requires such extension?
Would all of it be possible to cover with preferences? In the past, we've already discussed adding and supporting PreferenceStores per resource or Content-Type for other reasons (eg formatting settings), would this also cover the use-case here?

**Comment by mickaelistria** [comment]
Also, fundamentally, one purpose of the generic editor is to look and feel the same for all files. It's not an editor framework. So I'm not sure this fits in the goal.

**Comment by andrewL-avlq** [comment]
This is an attempt to address issues like https://github.com/eclipse-platform/eclipse.platform.ui/issues/866 in a generic extensible way. On that issue you suggest you would like to avoid having lots of preferences to set, so this extension point avoids using the PreferenceStore and is limited in scope to just the content assistant - of course an implementer of the extension point could connect to the PreferenceStore if they wished.
Happy to narrow the interface (maybe only the feature enablement methods?) and/or remove the content type specific registration if that will help.

**Comment by mickaelistria** [comment]
Genericity and extensibility is not always best. Could we instead first make the editor lookup preferences for those settings, and allow RCP products to override those preferences?

**Comment by andrewL-avlq** [comment]
So if I understand you correctly, you would prefer to see an implementation where the GenericContentAssistant got its look and feel settings from a PreferenceStore. Would you be ok for these preferences to be without a UI component? If so, I'll put together a PR for that.

**Comment by mickaelistria** [comment]
Yes, I think an approach relying on preferences would be IMO more consistent with the expectations.
Note that the report in #866 isn't much up to date, several improvements to the current state (without preferences but changing defaults) were already submitted by @rubenporras and merged IIRC.

**Comment by rubenporras** [comment]
Hi @mickaelistria ,

thanks for cross checking. @andrewL-avlq and me are working together in the same project. Yes, I did several improvements to the current state but we still need to be able to disable the autocompletion on type because for our languages it is not useful, so we decided to implement a configuration option.

Regards

**Comment by mickaelistria** [comment]
OK. I still think that an approach based on Preferences would be preferred. Once we have a PreferenceStore, next steps can be to create new stores: a content-type specific store, a resource/folder specific one... and then it would be easily possible to implement preference pages to configure one store or the other if we want users to face it.

**Pull request closed without merging**
