### PR TITLE
Remove blank Javadoc 3

### PR DESCRIPTION
**Pull request by jukzi**
This commit cleans up Javadoc that does not add information. It resolves ecj warnings:
 `Javadoc: Description expected after ...`
It helps to prevent future empty javadoc by disabling missingJavaDoc warnings. This resolves
 `Javadoc: Missing ...`

The modification is a result of regular expression search&replace:

in files `*.java`
 `^[\s]*\*[\s]*(@return|@param[\s]*[^\s]+|@throws[\s]*[^\s]+)\R([\s]*\*[\s]*@|[\s]*\*/\R)`
 ->`$2`
 `^([\s]*\*[\s]*\R)([\s]*\*/\R)`
 ->`$2`
 `^[\S\t ]*/\*\*\R[\s]*\*/\R`
 ->``

in files `org.eclipse.jdt.core.prefs`
 `org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc(Comments|Tags)\=[^\s]*`
 ->`org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc$1\=ignore`

### CODE REVIEW

**Comment by jukzi** [comment]
ignoring random test fail https://github.com/eclipse-platform/eclipse.platform.ui/issues/882

**Comment by jukzi** [comment]
3/3 of https://github.com/eclipse-platform/eclipse.platform.ui/pull/1287

**Comment by iloveeclipse** [comment]
Jörg, please if you bump versions, always do a build in the IDE to see if there are API errors.
Unfortunately Tycho API check still has not reached 1:1 functionality of the API tooling in the IDE, see https://github.com/eclipse-pde/eclipse.pde/pull/940#discussion_r1409827226

With this PR there will be an API error, see https://github.com/eclipse-platform/eclipse.platform.ui/pull/1348 with the fix.

**Comment by jukzi** [comment]
I don't understand: i only bumped where the build requested so. 
Unfortunately IDE API check runs in so many false positives, that i have it disabled.

**Comment by jukzi** [comment]
i understand, that i bumped 100 too far
image
but wonder why the build requested to do so.

**Pull request merged**
