### PR TITLE
Stop requiring jdt.ui in o.e.ui.tests

### PR DESCRIPTION
**Pull request by akurtakov**
There are enough resources available to handle tests without loading JDT UI and putting extra requirements and circular dependencies between repositories.

### CODE REVIEW

**Comment by vogella** [comment]
LGTM

**Comment by akurtakov** [comment]
Local runs improve from 21s to 8s for OpenCloseTest.

**Comment by jukzi** [comment]
> Local runs improve from 21s to 8s for OpenCloseTest.

Good job!

**Comment by akurtakov** [comment]
Tests worked without OOM but apitools failed. Merging.

**Comment by jukzi** [comment]
running UiTestSuite locally i still see jdt and jdt.ui in stacktraces - did i do something wrong?:

```
testConfigurationCloseImportedProjects: setUp...

!ENTRY org.eclipse.jdt.core 4 0 2024-12-10 18:07:02.940
!MESSAGE ImportExistingProjectsWizardTestRebuildProject does not exist
!STACK 1
Java Model Exception: Error in Java Model (code 969): ImportExistingProjectsWizardTestRebuildProject does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2535)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2329)
	at org.eclipse.jdt.internal.core.JavaProject.getOutputLocation(JavaProject.java:2144)
	at org.eclipse.jdt.internal.ui.wizards.importer.JDTProjectNatureImportConfigurator.getFoldersToIgnore(JDTProjectNatureImportConfigurator.java:89)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob.importProjectAndChildrenRecursively(SmartImportJob.java:462)
	at org.eclipse.ui.internal.wizards.datatransfer.SmartImportJob$1.run(SmartImportJob.java:223)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2024-12-10 18:07:02.941
!MESSAGE ImportExistingProjectsWizardTestRebuildProject does not exist

```

**Pull request merged**
