### PR TITLE
Merge platform text

### PR DESCRIPTION
**Pull request by laeubi**
See 
- https://github.com/eclipse-platform/eclipse.platform.ui/discussions/433

### CODE REVIEW

**Comment by iloveeclipse** [comment]
The API check fails. Is this expected?
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.ui.workbench.texteditor.tests: Only qualifier changed for (org.eclipse.ui.workbench.texteditor.tests/3.14.0.v20230628-0622). Expected to have bigger x.y.z than what is available in baseline (3.14.0.v20230316-1200) -> [Help 1]
```

**Comment by akurtakov** [comment]
Version bumps will be needed as compare versions uses git commit and moving to another repo makes it not match for sure.

**Comment by laeubi** [comment]
I'm currently adding the required bumps ...

**Comment by laeubi** [comment]
Version bumps applied and build succeeds now!

So this is ready to be merged.

**Comment by akurtakov** [comment]
@iloveeclipse would you please verify the git history is in good shape and I'll take care of the rest.

**Comment by vogella** [comment]
Thanks @laeubi for handling this.

**Comment by iloveeclipse** [comment]
> @iloveeclipse would you please verify the git history is in good shape and I'll take care of the rest.

Seem to be OK, please continue with the rest :-)

**Comment by laeubi** [comment]
I have now transferred all open issues to this repository, will now proceed with notification of pull requests.

**Comment by laeubi** [comment]
All PRs are closed with a hint to the new location.

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/32/console failed with
```
[ERROR] Failed to execute goal org.codehaus.mojo:license-maven-plugin:2.0.0:update-file-header (first) on project org.eclipse.jdt.ui.junit.sampleproject: Execution first of goal org.codehaus.mojo:license-maven-plugin:2.0.0:update-file-header failed: Plugin org.codehaus.mojo:license-maven-plugin:2.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:license-maven-plugin:jar:2.0.0 -> org.apache.maven:maven-artifact:jar:3.5.4: Failed to read artifact descriptor for org.apache.maven:maven-artifact:jar:3.5.4: The following artifacts could not be resolved: org.apache.maven:maven-artifact:pom:3.5.4 (absent): Could not transfer artifact org.apache.maven:maven-artifact:pom:3.5.4 from/to tycho-snapshots (https://repo.eclipse.org/content/repositories/tycho-snapshots/): status code: 403, reason phrase: Forbidden (403) -> [Help 1]
```

I assume this is our infra issue.
I see Alex triggered new build: 
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/33/

**Comment by iloveeclipse** [comment]
Failed due other issue: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/33/console
```
16:54:26  fatal: unable to access 'https://github.com/eclipse-jdt/eclipse.jdt.git/': Could not resolve host: github.com
16:54:26  fatal: run_command returned non-zero status for eclipse.jdt
```

**Comment by merks** [comment]
I've also seen such infrastructure problems just now:

https://ci.eclipse.org/emf/job/build/job/PR-6/1/console

Some connectivity issue...

**Comment by iloveeclipse** [comment]
@akurtakov : looking at https://www.eclipsestatus.io we probably should wait a bit?

**Comment by akurtakov** [comment]
No other choice it looks

**Comment by iloveeclipse** [comment]
I've reported https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3327

**Comment by iloveeclipse** [comment]
@laeubi : please update README & delete all other content on platform text.

**Pull request merged**
