### PR TITLE
Improvement to the existing Light Theme

### PR DESCRIPTION
**Pull request by mvm-sap**
For the full details of the change including screenshots see issue:  https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

### CODE REVIEW

**Comment by laeubi** [comment]
@mvm-sap please share Screenshot before/after the change

**Comment by vogella** [comment]
Please also adjust Linux light theme

**Comment by mvm-sap** [comment]
Please find the screenshots in the issue link provided : https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

**Comment by thomasritter** [comment]
@vogella Adjusting the themes is very expensive. It took one person 3+ months to learn about how the themes work and get the Windows and Mac themes ready. Before we adjust the Linux theme we want to be sure that the Eclipse community approves the made changes and incorporate their feedback. Once Windows and Mac are finished we are fully committed to update the Linux theme.

**Comment by vogella** [comment]
LGTM on Windows.

@thomasritter and @mvm-sap please watch out for reported issues over the next days and please provide ASAP the Linux theme changes so that I can also test these changes in my daily usage (and of course to have consistant theming).

**Pull request merged**
