### PR TITLE
delete WorkbenchCommandSupport "API is scheduled for deletion"

### PR DESCRIPTION
**Pull request by jukzi**
fix "overriding a synchronized method without being synchronized" and several deprecation warnings

### CODE REVIEW

**Comment by jukzi** [comment]
@vogella is it OK straight delete an unused API marked for deletion at this stage?

**Comment by vogella** [comment]
> @vogella is it OK straight delete an unused API marked for deletion at this stage?

The process is described here: https://github.com/eclipse-platform/eclipse.platform/blob/master/docs/ApiRemovalProcess.md I don't see the annotation in your commit so you need to check (and potentially update) https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fporting%2Fremovals.html if the freeze period for this API is already gone.

**Comment by jukzi** [comment]
the code deleted is annotated with ancient
```
	 * @deprecated Please use {@link IServiceLocator#getService(Class)} instead.
	 *             This API is scheduled for deletion, see Bug 431177 for details
	 * @noreference IWorkbenchCommandSupport is scheduled for deletion.
```

**Comment by vogella** [comment]
Yes, this API can be deleted, I marked that for deletion a long time ago. Please move also the entry in https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fporting%2Fremovals.html to the deleted API section.

**Comment by jukzi** [comment]
> Please move also the entry

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1748

**Comment by jukzi** [comment]
how to get rid of this errors?
```
09:25:24.894 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.5-SNAPSHOT:verify (verify) on project org.eclipse.ui.workbench: There are API errors:
09:25:24.894 [ERROR] META-INF/MANIFEST.MF:0 The type org.eclipse.ui.commands.AbstractHandler has been removed from org.eclipse.ui.workbench_3.131.100
...
09:25:24.894 [ERROR] META-INF/MANIFEST.MF:0 The type org.eclipse.ui.commands.Priority has been removed from org.eclipse.ui.workbench_3.131.100
09:25:24.894 [ERROR] META-INF/MANIFEST.MF:5 The major version should be incremented in version 3.131.100, since API breakage occurred since version 3.131.0
```

**Comment by laeubi** [comment]
> how to get rid of this errors?

Add proper compatibility filter or increment the major version ...

**Comment by vogella** [comment]
> Add proper compatibility filter or increment the major version ...

Filter. Major version increase for planned API deletion was tried once (by me) and caused a storm of complaints. Therefore, the PMC decided that or planned API deletions we only increase the minor version and use API filter (quickfix) to hide the warnings from the API tools.

**Comment by jukzi** [comment]
I added filter with quick fix. The error on mac is unrelated. The "new ecj warnings" are false positives (added API warnings).
Can i submit?

**Comment by laeubi** [comment]
> The "new ecj warnings" are false positives (added API warnings). Can i submit?

They are not "false positives" pleas either fix API warnings or suppress them as well.

**Comment by jukzi** [comment]
> They are not "false positives" pleas either fix API warnings or suppress them as well.

Which so called "new" warnings exactly do you think is related to this PR?
https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-1563/6/eclipse/new/

**Pull request merged**
