### PR TITLE
Adding Onboarding commands to the resource perspective

### PR DESCRIPTION
**Pull request by vogella**
As a first contribution adds Quick Access, Show Keys and New Wizard to the resource perspective

For #633

### CODE REVIEW

**Comment by vogella** [comment]
A first contribution of commands to get the discussion starting. 


@marcushoepfner I looked to me that if I add / remove onboarding commands in the IDE I need to use the clean workspace option to see this change. Maybe a cleanup step in missing in the code

@BeckerWdf I also think we should add images but in gray similar to VS. I see if I can get the image generator to work again on my machine and will provide another PR if I'm succesful.

**Review by BeckerWdf — APPROVED** [review]
Looks like this on macOS:
image

**Comment by BeckerWdf** [comment]
> @BeckerWdf I also think we should add images but in gray similar to VS. I see if I can get the image generator to work again on my machine and will provide another PR if I'm succesful.

Yes pls. Best ist to take the SVG icon of the perspective and create a new (bigger and greayscaled) SVG out of it to generate the PNGs. SVG should then also be stored in the images repo.

@vogella: What about the onboarding text? Would you already add on in this PR?

**Comment by vogella** [comment]
> > @BeckerWdf I also think we should add images but in gray similar to VS. I see if I can get the image generator to work again on my machine and will provide another PR if I'm succesful.
> 
> Yes pls. Best ist to take the SVG icon of the perspective and create a new (bigger and greayscaled) SVG out of it to generate the PNGs. SVG should then also be stored in the images repo.

Can you do this? If I add a new svg file to the tree and regenerate the png files, it is ignored. Maybe an inconsistance of the inkscape version on Linux.

> @vogella: What about the onboarding text? Would you already add on in this PR?

Which text do you propose? VS has no text and I think it looks really good.

**Comment by vogella** [comment]
By the way, I plan to rename "Find Action" to "Show All Commands" like in VS which is much telling IMHO.

**Comment by vogella** [comment]
We also need a better name for the new wizard. "New" is not very telling. Proposals?

**Comment by vogella** [comment]
image

**Comment by vogella** [comment]
Also "Show Key Assists" feels like IT talk from the past. Maybe we should also find a better name. Suggestions are welcome.

**Comment by mickaelistria** [comment]
> Also "Show Key Assists" feels like IT talk from the past. Maybe we should also find a better name. Suggestions are welcome.

"List shortcuts"

**Comment by BeckerWdf** [comment]
> By the way, I plan to rename "Find Action" to "Show All Commands" like in VS which is much telling IMHO.

I never liked "Find Actions". Wasn't it  the "Quick Access" before?. I don't know if "Show All Commands" is correct because this now can do even more (e.g. perform searches e.g.).

**Comment by BeckerWdf** [comment]
> Which text do you propose? VS has no text and I think it looks really good.

I mean the text that is "Open a file or drop files here to open them." in the demo perspective (see https://github.com/eclipse-platform/eclipse.platform.ui/pull/657/files)

**Comment by vogella** [comment]
> > By the way, I plan to rename "Find Action" to "Show All Commands" like in VS which is much telling IMHO.
> 
> I never liked "Find Actions". Wasn't it the "Quick Access" before?. I don't know if "Show All Commands" is correct because this now can do even more (e.g. perform searches e.g.).

"Quick Access"  is  IMHO not telling anything to the user, so I think reverting this would be a step back. See the discussion here https://github.com/eclipse-platform/eclipse.platform.ui/pull/673

**Comment by vogella** [comment]
> > Also "Show Key Assists" feels like IT talk from the past. Maybe we should also find a better name. Suggestions are welcome.
> 
> "List shortcuts"

I like it. Please create a PR, my energy to discuss user facing names has already been consumed for today.

**Comment by vogella** [comment]
Unrelated test error, merging.

**Comment by vogella** [comment]
> > Which text do you propose? VS has no text and I think it looks really good.
> 
> I mean the text that is "Open a file or drop files here to open them." in the demo perspective (see https://github.com/eclipse-platform/eclipse.platform.ui/pull/657/files)

Good idea IMHO, please provide separate PR for this.

**Comment by akurtakov** [comment]
Gnome has a very good looking and readable "Shortcuts" 
image

**Comment by BeckerWdf** [comment]
> Can you do this? If I add a new svg file to the tree and regenerate the png files, it is ignored. Maybe an inconsistance of the inkscape version on Linux.

Generation can be done manually in Inkscape of with the Image Render from the images repo - this one does not interact with Inkscape at all.

**Comment by BeckerWdf** [comment]
> I like it. Please create a PR, my energy to discuss user facing names has already been consumed for today.

see #676

**Comment by vogella** [comment]
> > I like it. Please create a PR, my energy to discuss user facing names has already been consumed for today.
> 
> see #676

Thanks, this comment was intended for the "List shortcuts" suggestion from @mickaelistria but your PR is also very much welcomed.

**Comment by BeckerWdf** [comment]
> Thanks, this comment was intended for the "List shortcuts" suggestion from @mickaelistria

Ups.

**Pull request merged**
