### PR TITLE
Set explicit project encoding to UTF-8

### PR DESCRIPTION
**Pull request by Bananeweizen**
Avoid the newly introduced warning in all platform.ui projects.

### CODE REVIEW

**Comment by akurtakov** [comment]
Very welcome change, esp if you finish it :)

**Comment by Bananeweizen** [comment]
On this repo, it should be complete. For the other platform repos, the Oomph setup was still running when I went to sleep. :)

**Comment by akurtakov** [comment]
Fixing the warnings could be finished but bumping all the changed projects versions is far from it as could be seen in the failing check.

**Comment by akurtakov** [comment]
Completed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/428

**Pull request closed without merging**
