### PR TITLE
BrowserViewer: fix IllegalStateException #1398

### LINKED ISSUE #1398: IllegalStateException reported in the log on opening files or navigating in browser
- Start Eclipse 4.30
- Open any svg file 
- Warning below reported into the log
```
java.lang.IllegalStateException: call to beginTask() missing
	at org.eclipse.jface.action.StatusLineManager$1.worked(StatusLineManager.java:221)
	at org.eclipse.ui.internal.browser.BrowserViewer$3.changed(BrowserViewer.java:421)
	at org.eclipse.swt.browser.WebKit.lambda$15(WebKit.java:2492)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
```

Same in green:
- Start Eclipse 4.30 on Linux
- Open "Internal browser"
- Set any url and go there
- **Multiple** warnings like above reported in the log

This is a regression/side effect of https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077.

### PR DESCRIPTION
**Pull request by jukzi**
@iloveeclipse try this on linux, please

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Unfortunately no change, same stack:
```
java.lang.IllegalStateException: call to beginTask() missing
	at org.eclipse.jface.action.StatusLineManager$1.worked(StatusLineManager.java:221)
	at org.eclipse.ui.internal.browser.BrowserViewer$3.changed(BrowserViewer.java:421)
	at org.eclipse.swt.browser.WebKit.lambda$15(WebKit.java:2492)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
```

**Comment by jukzi** [comment]
Then please debug what else called StatusLineManager.getProgressMonitor().new IProgressMonitor() {...}.done()

**Comment by iloveeclipse** [comment]
> Then please debug what else called StatusLineManager.getProgressMonitor().new IProgressMonitor() {...}.done()

It looks like it is not `done()` that is missing, but the monitor is different every time.
Not sure how it is supposed to work, as `org.eclipse.jface.action.StatusLineManager.getProgressMonitor()` always returns **new** monitor instance on every call. 

But looking in the history, I see that 7fe83e4b8b7d62b0b8b31971389599afaf0a27ca broke method contract from `IStatusLineManager.getProgressMonitor()`. It was originally stating "returns monitor", not it says "creates new monitor".

That is highly unexpected, especially the API method existed for a long time.
I don't know why I haven't realized that before while looking at https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077.

Anyway, please test this workaround on Windows: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1402
At least on Linux it shows proper progress now, without exceptions.

**Comment by iloveeclipse** [comment]
Closing, superceeded by https://github.com/eclipse-platform/eclipse.platform.ui/pull/1402.

However, if you've observed that there are missing updates on the flags and have steps to reproduce, please feel free to reopen, but provide steps to reproduce.

**Pull request closed without merging**
