### PR TITLE
added API Error example

### PR DESCRIPTION
**Pull request by jukzi**
DO NOT MERGE

https://github.com/eclipse-platform/eclipse.platform.ui/issues/2486

### CODE REVIEW

**Comment by jukzi** [comment]
@HannesWell the error message of "Pull-Request Checks" is not understandable in this case: `bundleLocation not found`

**Comment by jukzi** [comment]
Error should have been: org.eclipse.ui.browser/META-INF `The minor version should be incremented in version 3.8.400, since new APIs have been added since version 3.8.300`

**Comment by laeubi** [comment]
> error should have been: org.eclipse.ui.browser/META-INF `The minor version should be incremented in version 3.8.400, since new APIs have been added since version 3.8.300`

You have a missing since tag:
grafik

**Comment by laeubi** [comment]
And error is shown here

grafik

**Pull request closed without merging**
