### PR TITLE
Implement search-by-category for Import/Export wizard

### LINKED ISSUE #2576: New Wizard Dialog should also include Categories into Filter
If I search in the new project wizard for a category nothing is shown:

image

I would expect that all entries in the category are shown.

image

cc @ptziegler as he recently looked at the FilteredTree implementation.

### PR DESCRIPTION
**Pull request by ptziegler**
This adapts the WizardPatternFilter to also show the wizards, if the search string matches one of its containing categories.

Amends 532c0fb9b6851d77e3a7cc9f70a85c77a9ba3826
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2576

### CODE REVIEW

**Comment by vogella** [comment]
LGTM, tested it and works perfectly.

**Comment by ptziegler** [comment]
Example:

image

Note that there is a special implementation for the content provider which flattens categories with only a single child:

image

This behavior is intentional, but whether it's a "good" behavior is a different question...

https://github.com/eclipse-platform/eclipse.platform.ui/blob/187669501065220bf4fdb793e4409ae8ca807905/bundles/org.eclipse.ui.workbench/eclipseui/org/eclipse/ui/internal/dialogs/WizardContentProvider.java#L49-L52

**Comment by vogella** [comment]
> This behavior is intentional, but whether it's a "good" behavior is a different question...

So you suggest to remove this flattening?

**Comment by ptziegler** [comment]
> So you suggest to remove this flattening?

That would be my preference because the current behavior is not very intuitive. A `WizardCollectionElement` is flattened, if it doesn't have any other siblings. So the visibility of an element depends on your search string.

image

I found it confusion when `Test Import Add To Parent Category` was no longer a direct child of `General` after clearing the filter, even though that's exactly what the viewer told me.

However, this has been the behavior for over 20 years without any complaints. So I don't think the current behavior is wrong and if it is changed, then only as part of a separate commit.

**Comment by vogella** [comment]
> That would be my preference because the current behavior is not very intuitive. A `WizardCollectionElement` is flattened, if it doesn't have any other siblings. So the visibility of an element depends on your search string.

I agree that we should remove this special treatment, I think consistent behavior is the UI is important. As you already into the code, please provide a separate PR for this adjustment.

**Comment by vogella** [comment]
Linux builds seem to fail always unrelated to the actual change so I will assume that this is not related to this particular change. 

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.10:verify (verify) on project org.eclipse.ui.views.properties.tabbed: Execute ApiApplication failed

**Comment by vogella** [comment]
Linux build issue reported here: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2603

**Comment by ptziegler** [comment]
> Linux builds seem to fail always unrelated to the actual change so I will assume that this is not related to this particular change.
> 
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.10:verify (verify) on project org.eclipse.ui.views.properties.tabbed: Execute ApiApplication failed

The builds really are flaky... 😦 

>  As you already into the code, please provide a separate PR for this adjustment.

https://github.com/eclipse-platform/eclipse.platform.ui/pull/2604

**Comment by vogella** [comment]
The search test failure on Mac also seems unrelated, I checked them and I do not see the Wizard involved. Merging this one.

**Comment by vogella** [comment]
@ptziegler thanks, works great in todays I-Build. I think this is a notable feature, can you add it to N&N 4.5? I think the repo for this is: https://github.com/eclipse-platform/www.eclipse.org-eclipse?tab=readme-ov-file

**Pull request merged**
