### PR TITLE
Fix NPE when changing Eclipse theme

### LINKED ISSUE #60: NPE when changing Eclipse theme
Steps to reproduce:

1. Start Eclipse
2. Preferences -> General -> Appearance -> Theme
3. Change from Light to Dark or vice versa
4. Apply and Close 
5. at this point most of the UI is updated, but then the "Restart for theme..." prompt comes up
6. Press restart and the below stack trace will appear numerous times.

I did this in Eclipse IDE for C/C++ 2022-06 M2. I'll report back shortly if it occurs in platform build.

```java
!ENTRY org.eclipse.jface 4 0 2022-05-05 17:40:47.496
!MESSAGE An error has occurred. See error log for more details.
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.handlers.IHandlerService.deactivateHandler(org.eclipse.ui.handlers.IHandlerActivation)" because "service" is null
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:641)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:125)
	at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:927)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:461)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5798)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4481)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5798)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4481)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

### PR DESCRIPTION
**Pull request by BeckerWdf**
Fixes #60

### CODE REVIEW

**Review by laeubi — APPROVED** [review]
Looks good.

**Comment by BeckerWdf** [comment]
When clicking on the "Details" link for 
"continuous-integration/jenkins/branch Pending — This commit is being built" I get "HTTP ERROR 404 Not Found".
What's the issue there?

**Comment by BeckerWdf** [comment]
Can I still merge this pull request?

**Comment by BeckerWdf** [comment]
Why is "Pending — This commit is being built" 
What's the issue here? How can I move this PR forward?

**Comment by iloveeclipse** [comment]
> Can I still merge this pull request?

Independently on current state, we are in RC 1 time, so you **need** +1 from a project lead before merge.

**Review by mickaelistria — APPROVED** [review]
This change introduce no obvious risk of regression and is a bugfix, not feature work, not API... So +1 to merge as soon as build is OK with it.

**Comment by BeckerWdf** [comment]
> as soon as build is OK with it.

So what must I do to get the build OK?

**Comment by laeubi** [comment]
You pushed this directly to the repo instead of using a fork, thus you have two builds. One succeeds https://ci.eclipse.org/platform/job/eclipse.platform.ui/view/change-requests/job/PR-61/ and the other seems to be gone for whatever reason.

**Comment by mickaelistria** [comment]
Please do *not* push to this repo, but instead push to your own repo and use it to create a PR.

**Comment by BeckerWdf** [comment]
> Please do _not_ push to this repo, but instead push to your own repo and use it to create a PR.

If this should not be done we should configure the repo in a way that it's not possible.

**Pull request merged**
