### PR TITLE
Fix plugin customization for internal/external browser default #331

### LINKED ISSUE #331: Browser default preference for internal/external ignores plugin customization
A regression from: https://github.com/eclipse-platform/eclipse.platform.ui/commit/a2b25899e99bd9bc292d56a08e181878c9111068

https://bugs.eclipse.org/bugs/show_bug.cgi?id=577081

We use the following in a ```-pluginCustomization``` file:

```
org.eclipse.ui.browser/browser-choice=0
```

When resetting defaults, the setting in plugin customization is ignored.

### PR DESCRIPTION
**Pull request by trancexpress**
Adjusted the Web Browser preference page to respect defaults passed via -pluginCustomization file.

Fixes: #331

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Simeon, please bump bundle version

**Review by iloveeclipse — COMMENTED** [review]
LGTM except missing bundle version update

**Comment by trancexpress** [comment]
> Simeon, please bump bundle version

It was bumped already in August. It has to be bumped again?

**Comment by iloveeclipse** [comment]
> It was bumped already in August. It has to be bumped again?

It must be bumped **for the first change on current release**.
The last change wa son 4.25, in 4.26 this needs to be done again.
**Please in separated commit**, so it can be easily back ported.

**Comment by merks** [comment]
Note that the history shows the manifest change was tagged with S4_25_0_RC2: 

image

**Pull request merged**
