### PR TITLE
LTK Refactoring: fix progress report

### PR DESCRIPTION
**Pull request by jukzi**
Error was 'beginTask may only be called once'

tested with
org.eclipse.jdt.ui.tests.refactoring.RenamePackageTests.test2(), org.eclipse.ltk.core.refactoring.tests.participants.FailingParticipantTests

### CODE REVIEW

**Comment by jukzi** [comment]
ignoring random failing https://github.com/eclipse-platform/eclipse.platform.ui/issues/1183

**Comment by cdietrich** [comment]
@jukzi is it intentional some messages are no longer reported now
https://github.com/eclipse/xtext/issues/2836

**Comment by jukzi** [comment]
It is intentional that the progress is fixed. That for sure will change the progress.  Some "SetTaskName" may seem to be missing, as they are now incorporated in "BeginTask".
If you find an error in the progress please report a concrete example. The ProgressReportingTest seems to be usefull, can you add such test to this repo?

**Comment by cdietrich** [comment]
no if you say all changes are intentional i will adapt the test

**Pull request merged**
