### PR TITLE
Rename Text Editor into Plain Text Editor

### PR DESCRIPTION
**Pull request by mickaelistria**
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/1532 and https://github.com/eclipse-platform/eclipse.platform.ui/issues/1385

### CODE REVIEW

**Comment by mickaelistria** [comment]
@merks @vogella and what do you think about this (IMO simpler) one?

**Comment by merks** [comment]
I personally like the "Plain Text" qualifier; it sets low expectations as is appropriate.  That doesn't mean everyone will like it.  😝

**Comment by vogella** [comment]
I like this change.

**Comment by mickaelistria** [comment]
This one seems consensual enough: it was proposed on another issue, and is supported by the people who've been most active on related discussions. So let's just merge it now.

**Pull request merged**
