### PR TITLE
Prevent JobManager UI freeze when waiting for a rule in the UI Thread

### LINKED ISSUE #8: Prevent JobManager UI freeze when waiting for a rule in the UI Thread
This is a followup of discussions in https://github.com/eclipse-platform/eclipse.platform.ui/pull/6 and former Gerrit patch.

The general problem is that when one wants to run a job or some other operation protected by scheduling rules in UI Thread, and this scheduling rule is currently "blocked" by some other work, then the result is a UI Freeze.
We could do better by allowing the workbench/IDE parts to customize a bit the JobManager, more specifically the `beginRule` so it would show the interesting ProgressDialog when called from the UI Thread, so it doesn't seem too much like a freeze, and users have the opportunity to workaround it. It would also ease debugging.
Such a solution would allow to serve multiple operations that have implemented workarounds for this freeze, such as https://github.com/eclipse-platform/eclipse.platform.ui/pull/6 , and those workarounds could then be removed.

### PR DESCRIPTION
**Pull request by laeubi**
Just a draft for @jukzi

### CODE REVIEW

**Comment by laeubi** [comment]
By the way: for this to work more smooth, the default timed wait of 250ms in the Job API might be to long and could potentially feel lagging, I probably would reduce that to 100ms.

**Comment by vogella** [comment]
> By the way: for this to work more smooth, the default timed wait of 250ms in the Job API might be to long and could potentially feel lagging, I probably would reduce that to 100ms.

Sounds fine, but please create a new PR for this.

**Comment by mickaelistria** [comment]
Code looks very good. Can you please rework the commit message to make it more general and not only focus on JobManager? I think this code here is supposed to avoid UI freezes for most progress monitors, JobManager is just 1 consumer of those. This change may also require a rebase for the build to work.

**Comment by laeubi** [comment]
I only found this method used in the `JobManger`, can you give a reference where it is used elsewhere?

**Comment by mickaelistria** [comment]
You're right, sorry, I was confused with `org.eclipse.core.internal.utils.Policy.monitorFor()`. So it seems fine to keep this commit message as it.

**Comment by laeubi** [comment]
I rebased the change now.

**Comment by mickaelistria** [comment]
"on project org.eclipse.e4.ui.progress: Unqualified OSGi version 0.3.400.qualifier must match unqualified Maven version 0.3.300-SNAPSHOT for SNAPSHOT builds -"

**Comment by laeubi** [comment]
Next try :-\

**Comment by mickaelistria** [comment]
Thanks! That's a good change!

**Pull request merged**
