### PR TITLE
adopting Standard Platform Check Utility.

### PR DESCRIPTION
**Pull request by Sorna-Sarathi**
To Make use of Standard Utility Function for Platform Check wherever applicable.

### CODE REVIEW

**Comment by merks** [comment]
@Sorna-Sarathi 

You will need to sign the ECA for us to be able to accept contributions:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#setting-up-your-eclipse-and-github-account

**Comment by Sorna-Sarathi** [comment]
> @Sorna-Sarathi
> 
> You will need to sign the ECA for us to be able to accept contributions:
> 
> https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#setting-up-your-eclipse-and-github-account

> @merks 
>
> I have completed the ECA agreement.

**Comment by merks** [comment]
The build fails like this:
```
07:26:55.652 [ERROR] 	import org.eclipse.jface.util.Util;
07:26:55.652 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
07:26:55.652 [ERROR] The import org.eclipse.jface.util.Util is never used
07:26:55.652 [ERROR] -> [Help 1]
07:26:55.652 [ERROR] 
```

**Comment by Sorna-Sarathi** [comment]
> The build fails like this:
> 
> ```
> 07:26:55.652 [ERROR] 	import org.eclipse.jface.util.Util;
> 07:26:55.652 [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 07:26:55.652 [ERROR] The import org.eclipse.jface.util.Util is never used
> 07:26:55.652 [ERROR] -> [Help 1]
> 07:26:55.652 [ERROR] 
> ```

> Done. Removed the duplicate import library line.

**Comment by merks** [comment]
Thank you for contributing.  👍

**Pull request merged**
