### PR TITLE
Enable Chrome and Safari as web browsers in the preference page

### LINKED ISSUE #618: Chrome and Safari not detected under Web Browser tab in the Preference page.
Describe the bug
Selection of Web Browsers Chrome or Safari in the search tab will result in “No Web Browsers were Found“ error, despite these browsers being present in the system.

To Reproduce
Go to Eclipse->Settings->General->Web Browser
Select the Search tab->Go to Applications and select Google Chrome or Safari.

It will throw an error message as “No Web Browsers were Found“.

Screenshot 2023-02-27 at 10 32 59 PM

Platform MacOS

### PR DESCRIPTION
**Pull request by elsazac**
selection of Web Browsers Chrome or Safari in the search tab will result in “No Web Browsers were Found“ error, despite these browsers being present in the system.

Enable them by adding  relevant entries for these browsers in plugin.xml and plugin.properties.

Fixes: https://github.com/eclipse-platform/eclipse.platform.ui/issues/618

Before
Screenshot 2023-02-27 at 10 32 59 PM

After
Screenshot 2023-02-28 at 10 35 31 AM

/cc @lshanmug

### CODE REVIEW

**Comment by mickaelistria** [comment]
That looks OK to me.
@lshanmug @gayan @kthoms or anyone with a mac can verify/review it?
@elsazac Platform is currently frozen until it gets released in a couple of weeks; so this cannot be merged until master opens for 4.28 M1. If other mac users approve it, we'll try to merge it as soon as the master branch opens for development.

**Comment by mickaelistria** [comment]
Can you please add a commit that bumps the bundle version by +0.0.100 ?

**Comment by elsazac** [comment]
Yes.I will just update the change.

**Comment by elsazac** [comment]
> Can you please add a commit that bumps the bundle version by +0.0.100 ?

@mickaelistria done.Can you please have a look on this?

**Comment by mickaelistria** [comment]
@elsazac From build perspective, this looks good. However, I'm not familiar with mac things, so cannot fully review and decide to merge.
@SarikaSinha @kthoms Can you please review and maybe merge?

**Comment by SarikaSinha** [comment]
> @elsazac From build perspective, this looks good. However, I'm not familiar with mac things, so cannot fully review and decide to merge. @SarikaSinha @kthoms Can you please review and maybe merge?

@lshanmug Will be the right person to review this. Can you please review Lakshmi?

**Comment by lshanmug** [comment]
Thanks for the PR @elsazac 
Verified on Mac and looks good to merge.
@mickaelistria  But, not sure why the checks are failing, is it an intermittent issue?

**Comment by mickaelistria** [comment]
https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-619/3/ was successful, more recent build fail, log says repo.eclipse.org is not accessible and I can reproduce this issue locally, so it's an infra issue.
I would recommend we merge now even if this last build has failed, it all seemed correct a couple of days ago and nothing changed in this particular commit in the meantime.

**Comment by lshanmug** [comment]
@elsazac As a cleanup, I think we can remove the unsupported Camino and IE from the list of browsers on Mac and may be also add MS Edge as it's available on Mac.

**Pull request merged**
