### PR TITLE
[Oomph-Setup] Add eclipse.platform.ui configuration setup

### PR DESCRIPTION
**Pull request by HannesWell**
Additionally add a styled and drag&drop-able Oomph Configuration button.

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2430

### CODE REVIEW

**Comment by merks** [comment]
A configuration reference is needed:

image

Drag and drop the configuration resource onto the editor of the project setup, and alt-drag the Configuration instance and drop it onto the Configuration annotation.  (Ask me on slack if you need help.)

**Comment by HannesWell** [comment]
> A configuration reference is needed:
> 
> 
> Drag and drop the configuration resource onto the editor of the project setup, and alt-drag the Configuration instance and drop it onto the Configuration annotation. (Ask me on slack if you need help.)

Thanks for the hint! Just added it.

Since the verification build does not test this, I'll submit this to see if the Oomph badge is generated as expected by https://ci.eclipse.org/oomph/job/setup-archiver/.

**Comment by HannesWell** [comment]
> Since the verification build does not test this, I'll submit this to see if the Oomph badge is generated as expected by https://ci.eclipse.org/oomph/job/setup-archiver/.

Worked as expected:
grafik

And the displayed content also looks good:
https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.ui/master/releng/org.eclipse.ui.releng/platformUIConfiguration.setup&show=true

**Comment by merks** [comment]
You must have done something right. 🤪

**Pull request merged**
