### PR TITLE
Initialize onboarding information for all stacks in shared area #1773

### LINKED ISSUE #1773: Onboarding information (and primary data stack) lost when splitting editor area
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace (Java IDE product):

1. You start seeing the onboarding information in the shared area.
image
2. Open any two files and show them side-by-side by splitting the shared area.
image
3. Close the _left_ editor first, then close the remaining (originally _right_) editor. Now the onboarding information is lost.
image

It is expected to still have the onboarding information in the shared area after closing all editors, even if the area has been split before.

## Workaround

Opening a new workbench window (and closing the existing one) restores the shared area with the onboarding information.

## Tested under this environment
Issue is independent from environment. Lost onboarding information can be seen since 2023-06 release (i.e., since introduction of onboarding information), but underlying problem has been existing before. The screenshots are taken from the following system.
* OS & version: Windows 11 Enterprise, Build 22000.2777
* Eclipse IDE/Platform version (as shown in *Help > About*): Latest source code on 24.03.2024 on SDK I20240323-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

## Technical analysis

Whenever you split the shared area, so that it contains multiple part stacks, and then close the last editor in the original part stack (which is the "primaryDataStack"), the "primaryDataStack" will be lost.

The code that removes a part stack is this, precisely the call `ensureComposite(areaModel, stacks)`:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/AreaRenderer.java#L218-L231

When you close the last editor in the primary data stack, that part stack will simply be removed. Then no part stack being the primary and potentially also no part stack being tagged as `EditorStack` remains.

Interestingly, the part stacks with element id `PartStack@XXX` are no dangling references, That's just the result of some fallback code to ensure that every part stack has an element id:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java#L701-L704

## Expected technical behavior

I would expect the following behavior:
- When I instantiate a new part stack within the shared area (usually via drag&drop), it should also be marked as "EditorStack".
- When the part stack being the "primaryDataStack" is closed (which can only happen if the there are other part stacks in the shared area), the first remaining part should become the new "primaryDataStack".

The creation of a new part stack by splitting an area via drag & drop is handled in `SplitDropAgend2#drop()`:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.addons.swt/src/org/eclipse/e4/ui/workbench/addons/dndaddon/SplitDropAgent2.java#L293-L298
You can see that this new part stack will never be tagged as "EditorStack". When such a part stack becomes the last remaining in the shared area, without any editor open, the onboarding information is not shown as this depends on presence of exactly that tag:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6309193420f45895654d404d9f2adf875ca9432/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java#L709-L711

This issue has been detected when analyzing #1570. Once this issue has been addressed, #1570 should be revisited.

### PR DESCRIPTION
**Pull request by HeikoKlare**
The onboarding information is currently initialized for the primary editor stack in the shared area. When the shared area is split into multiple part stack showing editors side-by-side and closing the last editor in the original part stack, the onboarding information controls get lost together with that part stack.

With this change, onboarding information is embedded into every part stack of the onboarding area, such that when closing one of them, the information does not get lost. To this end, every part stack is in the shared area is tagged as an editor stack and the onboarding information is added to every tab folder of part stacks tagged as an editor stack.

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1773

### Discussion of alternatives

The change relies on tagging multiple part stacks as "EditorStack". An alternative solution would be to not check for the "EditorStack" tag but to check for a part stack being placed in the shared area. Necessary adaptations to productive code would be of similar complexity, but test adaptation effort would increase as the tests currently encode the contract of identifying part stacks requiring onboarding information by the "EditorStack" tag rather than being placed in the shared area.

### How to test / reproduce

You can experience the change with the following scenario (also documented in #1774):
1. Start an Eclipse product, e.g., an SDK
image
2. Open two editors in the shared area. Then split the shared area placing the the two editors side by side via drag and drop.
image
3. Close the _left_ editor first, then close the remaining (the originally _right_) editor. With the existing implementation, you will see that the onboarding information is lost.
image
With this change, the onboarding information is still present.
image

### CODE REVIEW

**Comment by HeikoKlare** [comment]
@marcushoepfner since you have contributed the onboarding functionality, may I ask you to have a look at this fix?

**Comment by marcushoepfner** [comment]
LGTM. Thanks @HeikoKlare 
I don't have a runnable IDE currently. Could you kindly check, whether two windows still works. Eclipse -> Menu -> Window -> New Window.
There was a bug. Refer to https://github.com/eclipse-platform/eclipse.platform.ui/issues/1180#issuecomment-1840403792

Thanks

**Comment by HeikoKlare** [comment]
Thanks for your feedback and the hint to the issue!
I have executed the problematic scenario described in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1180#issuecomment-1820953933 and played around with two workbench windows and did not find any issues (in particular not the one documented back then).

**Review by marcushoepfner — APPROVED** [review]

**Comment by HeikoKlare** [comment]
Thanks @marcushoepfner!

I'd like to postpose the merge of this PR after #1775 since that one becomes hard to reproduce manually once this PR has been merged.

**Pull request merged**
