### PR TITLE
Navigation History Entry - Issue #339

### PR DESCRIPTION
**Pull request by Greglar4**
Changes the implementation of the mergeInto method of the class NavigationHistoryEntry. This is to fix the reported github issue #339, where a user has multiple different editors whose EditorInputs are both FileEditorInputs with the same underlying file. Thus the editorInputs of the multiple editors were considered the same, and when navigating between the editors, the navigation history entries were being merged, incorrectly.

The supplied change checks both if the editor inputs and editorIDs of two navigation history entries are the same before merging the two navigation history entries.

### CODE REVIEW

**Comment by Greglar4** [comment]
I failed the ECA agreement check, but have now agreed to the ECA agreement in my Eclipse account.

**Review by mickaelistria — DISMISSED** [review]
2 editors using the same FileEditorInput usuually use the same underlying IDocument and are necessarily synchronized. The history is not really per editor but per document; so I don't think this patch is really valid.

**Comment by merks** [comment]
I've run into this problem too with clients.  In my case they were not using IDocuments and I worked around it with this approach using an editor ID.  Even if documents are shared and synchronized, the different editors can be in different locations in the document in the different editors.  So to me this looks like a good change that can only improve the user's experience. 

@mickaelistria I get the impression that your comment is somehow based on the concept editing history where synchronized shared document are relevant, but this change is about navigation history, i.e., what the left and right arrow in the toolbar do.  Is there perhaps a misunderstanding here?  This navigation history is an extensible framework and non-textual editor can plug into that...

**Review by mickaelistria — COMMENTED** [review]
@merks You're right, sorry, I misunderstood. Then it all makes more sense to me, I'm removing my negative review as it's not relevant here and leave it up to you and @Greglar4 to complete it as I've just demonstrated I'm not really reliable on that piece of code ;)

**Comment by merks** [comment]
@Greglar4 

It looks like the builds themselves are broken right now, unrelated to you changes, so I'll need to kick them again later...

The ECA is failing again, but that was passing before I think.  Are you have to access this page:

https://api.eclipse.org/git/eca/status/gh/eclipse-platform/eclipse.platform.ui/1150

For me it shows only a partial email address, but there is a field where you can enter a full email address; I just don't know if those things work for you....h

**Comment by Greglar4** [comment]
Checking my email address at the Git ECA Validation tool has it pass, but I noticed my github profile did not have an email address selected. I updated it to the email address that passes the validation tool, is this sufficient?

**Comment by Greglar4** [comment]
I have also edited my author and commiter email on the actual commit, if that was necessary.

**Comment by merks** [comment]
Can you amend the commit, ensure that the author email of the commit is the one associated with your eclipse account and force push that?

**Comment by merks** [comment]
The ECA passed so it looks promising.

**Comment by merks** [comment]
FYI, I'm just testing if merge in master fixes the build problems...

**Pull request merged**
