### PR TITLE
Find/Replace dialog: remove ring-tone #1908

### LINKED ISSUE #1908: [find/replace dialog] remove Ringtone
This Issue Documents a review-comment from the find/replace overlay PR
which could not be addressed into the current proposal:
[comment](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192#issuecomment-2033690701) by @HeikoKlare and @vogella 

In the PR for the Overlay, we decided to remove the Ringtone notifying of errors while searching, because it was perceived as annoying.
We should also remove it from the Dialog.

### PR DESCRIPTION
**Pull request by Wittmaxi**
Removes the beep which is issued after some unsuccessful operations in
the find/replace dialog.

fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1908

### CODE REVIEW

**Review by HeikoKlare — COMMENTED** [review]
I absolutely like the proposal to remove the beep functionality (and I think particularly @vogella will do as well 🙂).

Just two comments on the proposed changes:
1. The removal seems incomplete to me, as the `allowBeep` parameter in `evaluateFindReplaceStatus` is now unused. In my opinion, this should be cleaned up throughout the call hierarchy.
2. This change does not seem to depend on #1192 but currently contains the commit of that PR. You could rebase the single commit relevant for this PR onto master instead of the other PR.

**Comment by Wittmaxi** [comment]
@HeikoKlare I believe that the issues you just mentionned are addressed

**Review by HeikoKlare — APPROVED** [review]
Looks good now, thank you! I have added a version bump for 4.33 stream to see if builds run fine. In case this is merged after some other PR affecting the same project (like #1192), the version bump will be automatically removed via rebase.

**Comment by HeikoKlare** [comment]
Failing test is unrelated and already documented: #294

**Pull request merged**
