### PR TITLE
Find/Replace overlay: fix missing icon on Linux

### LINKED ISSUE #1960: find/replace overlay: "toggle" find/replace symbol not shown
Just seen that on Windows the toggle is supposed to be some filled arrow sign, which is obviously not the case for me on Linux:

image

I guess the symbol button uses/expects some font either not available or not configured as default one on my Linux machine.

That should be fixed. I wonder why don't we use a "simple" icon for that, or just draw that on screen instead of relying on fonts?

### PR DESCRIPTION
**Pull request by Wittmaxi**
grafik
grafik

Reintroduces Icons for opening/closing the replace area of the overlay. (and looks a bit better, IMHO ;-))

fixes #1960

### CODE REVIEW

**Comment by Wittmaxi** [comment]
@iloveeclipse with this PR, I believe I have addressed all three of your Linux-specific concerns :)

**Comment by iloveeclipse** [comment]
> with this PR, I believe I have addressed all three of your Linux-specific concerns :)

Thanks for fixing the button (works now), but could you name another two?

**Comment by Wittmaxi** [comment]
@iloveeclipse I was referring to

1) f6 crash
2) overlay not opening (in one specific PR)
3) this button not being shown

**Comment by Wittmaxi** [comment]
Mac fail seems unrelated @iloveeclipse - I believe we can merge this now! (Please don't forget merging the org.eclipse.images-PR)

**Comment by iloveeclipse** [comment]
> Please don't forget merging the org.eclipse.images-PR

Please give a link to that PR.

**Comment by Wittmaxi** [comment]
@iloveeclipse the .images pr is here: https://github.com/eclipse-platform/eclipse.platform.images/pull/74

**Pull request merged**
