### PR TITLE
Hide onboarding image when space is too less

### PR DESCRIPTION
**Pull request by marcushoepfner**
Issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/723

The onboarding image is hidden when there is less than 400 px vertical space for the tab folder.

Also centers image and text. Otherwise looks strange, refer to debug perspective onboarding which has a rather short text.

### CODE REVIEW

**Comment by marcushoepfner** [comment]
@vogella and @BeckerWdf, could you please state, whether you think 450 px feels good for you.

**Comment by vogella** [comment]
450 feels fine, thanks for working on this, you get more feedback on these changes after the merge... ;-)

**Comment by marcushoepfner** [comment]
This is how it looks on my computer:

https://github.com/eclipse-platform/eclipse.platform.ui/assets/29301444/00182213-a326-44b5-8244-3d1d79451885

**Comment by marcushoepfner** [comment]
> 450 feels fine, thanks for working on this, you get more feedback on these changes after the merge... ;-)

Had uploaded the wrong commit. Now code is up-to-date. 450 px!
I'll wait for the build and if everything is fine I'm going to merge

**Review by BeckerWdf — APPROVED** [review]

**Comment by iloveeclipse** [comment]
This PR causes regression on all platforms, see https://github.com/eclipse-platform/eclipse.platform.ui/issues/844.
Please consider to provide a fix ASAP.

**Comment by marcushoepfner** [comment]
Fix: https://github.com/eclipse-platform/eclipse.platform.ui/pull/845

**Pull request merged**
