### PR TITLE
Unit test for onboarding: ModeledPageLayoutTest

### PR DESCRIPTION
**Pull request by marcushoepfner**
Adds tests for PR
https://github.com/eclipse-platform/eclipse.platform.ui/pull/656

### CODE REVIEW

**Comment by jukzi** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/719 showed the same amount of errors. probably unrelated to this PR.

**Comment by marcushoepfner** [comment]
> #719 showed the same amount of errors. probably unrelated to this PR.

So I should just merge? This does not really looks like a safety net. More like a broken window house. How do I know whether my PR broke it or whether is was broken before already?!

Why are so many tests failing? Due to the github migration?

**Comment by iloveeclipse** [comment]
As long as you see `continuous-integration/jenkins/pr-head — This commit cannot be built` please never merge!

**Comment by iloveeclipse** [comment]
> #719 showed the same amount of errors. probably unrelated to this PR.

Note that `continuous-integration/jenkins/pr-head This commit looks good` status there differs from this PR!

**Comment by iloveeclipse** [comment]
I've rebased the test just to see if that is unstable or not.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
There are stable test fails if running in Jenkins:

[Test Result](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/) (31 failures / ±0)
[org.eclipse.ui.tests.preferences.ZoomAndPreferencesFontTest.testZoomCommand](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.preferences/ZoomAndPreferencesFontTest/testZoomCommand/)
[org.eclipse.ui.tests.commands.CommandExecutionTest.testCommandListenerExecuteClosePart](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandExecutionTest/testCommandListenerExecuteClosePart/)
[org.eclipse.ui.tests.commands.CommandExecutionTest.testCommandExecuteClosePart](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandExecutionTest/testCommandExecuteClosePart/)
[org.eclipse.ui.tests.commands.CommandExecutionTest.testCommandExecute](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandExecutionTest/testCommandExecute/)
[org.eclipse.ui.tests.commands.CommandExecutionTest.testCommandListenerExecute](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandExecutionTest/testCommandListenerExecute/)
[org.eclipse.ui.tests.commands.Bug74982Test.testSelectAllHandlerSendsSelectionEvent](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/Bug74982Test/testSelectAllHandlerSendsSelectionEvent/)
[org.eclipse.ui.tests.commands.Bug74990Test.testPartIdSubmission](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/Bug74990Test/testPartIdSubmission/)
[org.eclipse.ui.tests.commands.Bug417762Test.testSuggestionUseParameterizedCommandExecuteWithChecks](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/Bug417762Test/testSuggestionUseParameterizedCommandExecuteWithChecks/)
[org.eclipse.ui.tests.commands.Bug417762Test.testAsReported](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/Bug417762Test/testAsReported/)
[org.eclipse.ui.tests.commands.CommandParameterTypeTest.testSubtract](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandParameterTypeTest/testSubtract/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForNegativeNumber](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForNegativeNumber/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testBasicHandler](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testBasicHandler/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testLocalContext](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testLocalContext/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak123](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak123/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak132](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak132/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak213](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak213/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak231](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak231/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak312](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak312/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testForBreak321](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testForBreak321/)
[org.eclipse.ui.tests.commands.HandlerActivationTest.testTwoHandlers](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/HandlerActivationTest/testTwoHandlers/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testNoParametersWithCallbacks](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testNoParametersWithCallbacks/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testCommandThroughWindow](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testCommandThroughWindow/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testCallbackCleanup](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testCallbackCleanup/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testParametersWithCallbacks](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testParametersWithCallbacks/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testParmsToDifferentProtocol](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testParmsToDifferentProtocol/)
[org.eclipse.ui.tests.commands.CommandCallbackTest.testParmsToSameCommand](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.commands/CommandCallbackTest/testParmsToSameCommand/)
[org.eclipse.ui.tests.menus.MenuVisibilityTest.testVisibilityTracksEnablement](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.menus/MenuVisibilityTest/testVisibilityTracksEnablement/)
[org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testSingleFileWithEditorSplit](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.internal/WorkbookEditorsHandlerTest/testSingleFileWithEditorSplit/)
[org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testFileWithNameConflictWithEditorClonedTwice](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.internal/WorkbookEditorsHandlerTest/testFileWithNameConflictWithEditorClonedTwice/)
[org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testMultipleFilesWithNameCollisionAndEditorSplit](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.internal/WorkbookEditorsHandlerTest/testMultipleFilesWithNameCollisionAndEditorSplit/)
[org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testSingleFileWithEditorClonedTwice](https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-703/4/testReport/junit/org.eclipse.ui.tests.internal/WorkbookEditorsHandlerTest/testSingleFileWithEditorClonedTwice/)

**Comment by iloveeclipse** [comment]
You've merged master to your branch. Please avoid merge commits, and use rebase on master instead.

**Comment by marcushoepfner** [comment]
> You've merged master to your branch. Please avoid merge commits, and use rebase on master instead.

Sorry. I was not aware of. Maybe the Github UI did it.
Do I need to change something?

**Comment by iloveeclipse** [comment]
> Do I need to change something?

Yes. Following steps are for Eclipse EGit, **NOT** for github UI.
1) Create a temporary `temp` branch on current head of `unit_tests_for_onboarding_II` branch.
2) Checkout `master` branch
3) Pull latest commits from github https://github.com/eclipse-platform/eclipse.platform.ui
4) Hard reset `unit_tests_for_onboarding_II` branch on latest master commit, or if you can't anymore, on first common commit between master and `unit_tests_for_onboarding_II` branch.
5) Make sure `unit_tests_for_onboarding_II` head is on same commit with latest `master`.
6) Cherry-pick **your** commits from temporary `temp` branch to `unit_tests_for_onboarding_II` branch.
7) Force push to github.

In the future, always "fetch" latest commits to master branch and rebase your branch on master instead of merging with it.

**Comment by marcushoepfner** [comment]
> > Do I need to change something?
> 
> Yes. Following steps are for Eclipse EGit, **NOT** for github UI.
> 
>     1. Create a temporary `temp` branch on current head of `unit_tests_for_onboarding_II` branch.
> 
>     2. Checkout `master` branch
> 
>     3. Pull latest commits from github https://github.com/eclipse-platform/eclipse.platform.ui
> 
>     4. Hard reset `unit_tests_for_onboarding_II` branch on latest master commit, or if you can't anymore, on first common commit between master and `unit_tests_for_onboarding_II` branch.
> 
>     5. Make sure `unit_tests_for_onboarding_II` head is on same commit with latest `master`.
> 
>     6. Cherry-pick **your** commits from temporary `temp` branch to `unit_tests_for_onboarding_II` branch.
> 
>     7. Force push to github.
> 
> 
> In the future, always "fetch" latest commits to master branch and rebase your branch on master instead of merging with it.

I have two remotes, the upstream (eclipse git repo) and origin (my fork of that).
I usually do:
1. fetch from upstream
2. rebase local branch on upstream
3. push -f to origin

Maybe it was indeed the github ui. Vogella was complaining as well some weeks ago.

Solution was even shorter than what you did:
1. create a new local branch based on upstream/master
2. cherry pick my commit
3. resolve merge conflicts
4. push to my fork

**Comment by marcushoepfner** [comment]
@iloveeclipse can I get your review please? Github tells me, you requested change.

**Comment by marcushoepfner** [comment]
@vogella @laeubi in this commit I wrote a test for the onboarding code in [ModeledPageLayout.java](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/e4/compatibility/ModeledPageLayout.java).

I setup an Eclipse context and some other mocks in this test.
Though I do `IEclipseContext.dispose()` in teardown this is breaking other tests like 

- HandlerActivationTest
- CommandCallbackTest

I have no clue why? I tried different things but nothing helped.

Without my test (e.g. on main branch) HandlerActivationTest and others are not failing.

In #704 I did similar with IEclipseContext in [PerspectiveExtensionReaderTest](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/tests/org.eclipse.ui.tests/Eclipse%20UI%20Tests/org/eclipse/ui/tests/api/PerspectiveExtensionReaderTest.java) and no other tests broke.

I'm asking you because I think the both of you have knowledge in e4. 
Can you have a look please. Help would be very appreciated. Thank you.

**Comment by laeubi** [comment]
@marcushoepfner I can't find anything particular form E4 but this looks how it _might_ can cause trouble:

```
platformUIMock = Mockito.mockStatic(PlatformUI.class);
platformUIMock.when(() -> PlatformUI.getWorkbench()).thenReturn(workbenchMock);
```

**Comment by marcushoepfner** [comment]
> @marcushoepfner I can't find anything particular form E4 but this looks how it _might_ can cause trouble:
> 
> ```
> platformUIMock = Mockito.mockStatic(PlatformUI.class);
> platformUIMock.when(() -> PlatformUI.getWorkbench()).thenReturn(workbenchMock);
> ```

I removed it completely but still the same tests are failing.

**Comment by laeubi** [comment]
maybe you can comment out the code and then add it selectively so we see what triggering it, the assertions are a bit vague at laest there are other tests that use a similar setup like yours and they seem to work.

**Comment by marcushoepfner** [comment]
After a lot of commenting and pushing I found out, that actually #704 is causing the issues.
As soon as another test is added to [ApiTestSuite.java](tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/api/ApiTestSuite.java) after PerspectiveExtensionReaderTest a lot of command and handler tests are red.

I will revert #704 and then check if this (#703) will work.

**Comment by marcushoepfner** [comment]
After https://github.com/eclipse-platform/eclipse.platform.ui/pull/704 was reverted I rebuild this one. Even with another dummy unit test (after ModeledPageLayoutTest in the APITestSuite) to be sure this time, that it work.
I will analyze next week why #704 had issues. I guess it is due to the extension point implementation there.

Everything was fine. 

I have removed the dummy unit test now and after the build is ok, we can merge from my point of view.

@iloveeclipse, I would need a review for this PR here, at least github tell me that I cannot merge before your review since you have requested change.

**Comment by marcushoepfner** [comment]
...aaarrghhhh
Again issues! I don't understand this anymore. I have to re-analyze why this is failing again though it was ok in the prev. build with just another dummy unit test class in the test suite.

**Comment by marcushoepfner** [comment]
@iloveeclipse Github says, you requested change. Guess that is solved? Was reagarding the failing tests. No test is failing anymore.
I'd like to merge, could you please approve if ok for you.

**Review by iloveeclipse — APPROVED** [review]

**Pull request merged**
