### PR TITLE
ProgressIndicator: add possibility to set progress back and forth. #327

### PR DESCRIPTION
**Pull request by jukzi**
Do not reset progress to 0 when updating ProgressAnimationItem.

### CODE REVIEW

**Comment by jukzi** [comment]
@merks can you test if that change helps?

**Comment by fabioz** [comment]
Just to note, I applied this PR locally and it seems to work for me.

**Comment by vogella** [comment]
Thanks @jukzi, lets see if that fixes it. @merks and @fabioz (hey, nice to see that you are stilll around), please test in the next I-Build.

**Comment by fabioz** [comment]
> nice to see that you are stilll around

@vogella Nice to see you around too :) -- unfortunately I don't really have that much time to develop Eclipse itself, but I still use it daily and I'm still doing PyDev...

**Pull request merged**
