### PR TITLE
AboutPluginsPage: show signed Date in column (lazy, sortable)

### PR DESCRIPTION
**Pull request by jukzi**
Also adapt column width to show most values without ellipsis

### CODE REVIEW

**Comment by jukzi** [comment]
before:
image

after:
image

**Comment by merks** [comment]
That's a lot of detail.  Do you think it's ever important to know the time of day, down to the exact second?

**Comment by jukzi** [comment]
> That's a lot of detail. Do you think it's ever important to know the time of day, down to the exact second?

For me its most important see the day. I just took the format that was already used in that dialog.

**Comment by jukzi** [comment]
i'll change to short:
image

**Pull request merged**
