### PR TITLE
Fix API errors by updating bundle versions

### LINKED ISSUE #2430: API errors on org.eclipse.ui.editors and org.eclipse.ui.workbench.texteditor
Regression from commit 9bd3284d67ef8703bb29453a12dca20520a96c61 / https://github.com/eclipse-platform/eclipse.platform.ui/pull/2400

- New constant was added in `AbstractDecoratedTextEditorPreferenceConstants` API (`org.eclipse.ui.editors`)
- New method was added to `SourceViewerDecorationSupport` (`org.eclipse.ui.workbench.texteditor`)

In both cases minor segment version should have been updated. Interestingly, no checks failed...

I will push updated manifests.

### PR DESCRIPTION
**Pull request by iloveeclipse**
Regression from commit 9bd3284 / #2400

Also updated version range on bundle with increased version.

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2430

### CODE REVIEW

**Comment by iloveeclipse** [comment]
```
Exception in thread "Active Thread: Equinox Container: aa943991-8bd5-44f7-a55a-1a7bc7647820" java.lang.OutOfMemoryError: Java heap space
Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:118)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:38)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

Where is **that** coming from? Is this code regression or infrastructure change?

**Comment by iloveeclipse** [comment]
@laeubi : Looking at the tycho command line output, I wonder why do we have **no** summary report about number of API warnings/errors for `org.eclipse.ui.editors` (compared to `org.eclipse.ui.workbench.texteditor`)?

What causes this difference (see log https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-2431/1/consoleFull)?
 
```
07:47:52.107 [INFO] --- tycho-apitools:4.0.8:verify (verify) @ org.eclipse.ui.editors ---
07:47:52.108 [INFO] Resolve API baseline for org.eclipse.platform:org.eclipse.ui.editors:eclipse-plugin:3.19.0-SNAPSHOT with linux/gtk/x86_64
07:48:11.819 [INFO] API Analysis finished in 19 s.
```

```
07:47:33.181 [INFO] --- tycho-apitools:4.0.8:verify (verify) @ org.eclipse.ui.workbench.texteditor ---
07:47:33.182 [INFO] Resolve API baseline for org.eclipse.platform:org.eclipse.ui.workbench.texteditor:eclipse-plugin:3.19.0-SNAPSHOT with linux/gtk/x86_64
07:47:43.699 [INFO] API Analysis finished in 10 s.
07:47:43.699 [INFO] 0 API ERRORS
07:47:43.699 [INFO] 0 API warnings
```

**Comment by iloveeclipse** [comment]
> Where is **that** coming from? Is this code regression or infrastructure change?

Created https://github.com/eclipse-platform/eclipse.platform.ui/issues/2432 fur further investigation.

**Comment by iloveeclipse** [comment]
For the record, test failures are unrelated (see https://github.com/eclipse-platform/eclipse.platform/issues/1592):

image

Merging.

**Comment by BeckerWdf** [comment]
thanks for fixing this.

**Pull request merged**
