### PR TITLE
Window Title: Add preference to show/hide editor tooltip part

### PR DESCRIPTION
**Pull request by pramhegde**
The workbench window title can currently be customized to display workspace name, perspective name, full path and product name. The active editor name is shown as a part of the window title but is not customizable in the preferences page. This change makes the active editor info customizable.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Could you add some screenshots showing what is changed in preferences and in window title?

**Comment by pramhegde** [comment]
Sure
With active editor name
Without active editor name

**Review by BeckerWdf — APPROVED** [review]

**Review by BeckerWdf — APPROVED** [review]

**Comment by BeckerWdf** [comment]
Thanks for your very first contribution 🎉

**Comment by merks** [comment]
Yes, this is a cool and useful new feature.  Thanks!  🥇

**Pull request merged**
