### PR TITLE
Bug #375 - jface High-DPI: FileImageDescriptor's autoscaling strategy unnecessarily restricted to quadratic images

### PR DESCRIPTION
**Pull request by Dani-Hub**

### CODE REVIEW

**Comment by Dani-Hub** [comment]
I'd like to get some help how to resolve the build error properly:

> Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jface.tests: Only qualifier changed for (org.eclipse.jface.tests/1.3.700.v20221002-0925). Expected to have bigger x.y.z than what is available in baseline (1.3.700.v20220720-2118)

So what is the recommended version change that I should make? Should I just increase the third version digit by 100?

**Comment by laeubi** [comment]
> Should I just increase the third version digit by 100?

Correct!

**Comment by laeubi** [comment]
Cna you please rebase on master and squash all your changes into one commit?

**Comment by Dani-Hub** [comment]
> Cna you please rebase on master and squash all your changes into one commit?

Hmmh, I'm not an GIT expert, so I'm not sure how to realize that request. Could you give me a more detailed description, please? (Rebase on master is not the problem here)

**Comment by laeubi** [comment]
The easiest way would be:

1. Create a new branch from the "upstream" master branch (in Eclipse right-click > Team > switch to > new branch > select ... > enter "master" in the search field e.g. name it "issue_377_rebase" branch from 
2. Now choose Team > Merge and choose the "Squash" option togehter with branch where your current changes live, what seems the master branch of the "origin"
3. Now you review your changes, enter a descriptive commit message and push your branch (you can simply open a new PR then).

**Comment by Dani-Hub** [comment]
> The easiest way would be:
> 
>     1. Create a new branch from the "upstream" master branch (in Eclipse right-click > Team > switch to > new branch > select ... > enter "master" in the search field e.g. name it "issue_377_rebase" branch from

OK, I did so.

>     2. Now choose Team > Merge and choose the "Squash" option togehter with branch where your current changes live, what seems the master branch of the "origin"
> 

Hmmh, I'm not quite sure about that one. I thought I did so, but it tells me now that "I'm already up to date" - sigh.

**Comment by laeubi** [comment]
You should create the new branch on [eclipse-platform:master](https://github.com/eclipse-platform/eclipse.platform.ui)

and squash changes from [Dani-Hub:master](https://github.com/Dani-Hub/eclipse.platform.ui)

**Comment by Dani-Hub** [comment]
> You should create the new branch on [eclipse-platform:master](https://github.com/eclipse-platform/eclipse.platform.ui)
> 
> and squash changes from [Dani-Hub:master](https://github.com/Dani-Hub/eclipse.platform.ui)

Thanks for your patience and explanation. It seems that I finally made it ;-) Feel free to close this older PULL request now.

**Comment by laeubi** [comment]
No problem, replaced by https://github.com/eclipse-platform/eclipse.platform.ui/pull/379

**Pull request closed without merging**
