### PR TITLE
spare control characters from content assist trigger

### PR DESCRIPTION
**Pull request by elsazac**
Fixes :#891

### CODE REVIEW

**Comment by mickaelistria** [comment]
Is Ctrl+Space trigger still working with this change?

**Comment by elsazac** [comment]
> Is Ctrl+Space trigger still working with this change?

Yes it works.

**Comment by elsazac** [comment]
I think `CTRL+SPACE` is handled in ProposalSelectionListener and does not intervene here.

**Comment by merks** [comment]
I added some print statements to see when the method is called.  It's kind of confusing that sometimes it's called but often it's not.  I.e., one would expect it not to be called by Ctrl-S because that triggers a save action.  That's sort of true, but if the editor isn't dirty the action isn't triggered and the event does come through.  That would be the reason why pressing Ctrl-S a couple of times causes the issue.

Then I wondered about the origin  "ALT" and saw it come from this:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=176698

So I suppose this change is safe, though it still feels slightly uncomfortable.  

@akurtakov 

I'm not sure who else would be "qualified" to review this change?

@szarnekow

Often Sebastian has a keen eye.

**Review by mickaelistria — APPROVED** [review]
I also spent some time looking at this in more details earlier today, and this seems like a good fix. I'm not aware of anyone who would miss a content-assist popup when hitting a key with Ctrl or Cmd keys on; it seems totally safe to assume someone hitting one of those keys is *not* willing to enter text directly in the editor but want to operate a more complex operations, potentially outside of the editor, and as a consequence, that they're not in a case where automatic trigger of content-assist make sense.

**Comment by merks** [comment]
@mickaelistria 

I appreciate the confirmation!

**Pull request merged**
