### PR TITLE
Align Commands in Onboarding Composite

### PR DESCRIPTION
**Pull request by marcushoepfner**
Issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/753

### CODE REVIEW

**Comment by marcushoepfner** [comment]
First version which looks like this:

Screenshot 2023-05-11 at 13 53 53
Screenshot 2023-05-11 at 13 54 07

Should there be a colon?

**Review by BeckerWdf — APPROVED** [review]

**Comment by BeckerWdf** [comment]
> Should there be a colon?

I don't miss a colon.

**Comment by iloveeclipse** [comment]
StackRendererTest.testOnboardingIsFilled test fails now.

**Review by BeckerWdf — APPROVED** [review]

**Comment by marcushoepfner** [comment]
PipelineChainTest.java is failing. Not related to this change, refer to #757 .
Mergin and closing this one.

**Comment by iloveeclipse** [comment]
> Mergin and closing this one.

Currently we are working towards 4.28 RC1.

Note: if you are not subscribed to https://accounts.eclipse.org/mailing-list/platform-dev, please do. There are reminders sent before/after each phase, like https://www.eclipse.org/lists/platform-dev/msg03811.html and https://www.eclipse.org/lists/platform-dev/msg03817.html

Please next time don't merge PR's during RC phase.

**Comment by marcushoepfner** [comment]
I would have expected the build (code freeze job) to tell me so.
I'm subscribed already, but have to admit that I usually not read them all. Now that I know this, I'll read more careful.

But why is the code freeze job not failing in this case.

**Comment by iloveeclipse** [comment]
> I would have expected the build (code freeze job) to tell me so.

Well, it obviously failing to fail the build. I've created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1079.

> But why is the code freeze job not failing in this case.

There were other fails which you shouldn't ignore either, like `check-merge-commits / Block Merge Commits`:

image

Please next time be more careful merging PR's.

Note: this one still needs a `project lead or PMC vote on the bug report`, otherwise it should be reverted so it doesn't add any regression during RC time. 

I'm overcommitted with other tasks to perform the review here and vote for reverting it, so please if you want thos PR be in the RC1, please ask someone else to approve (see https://projects.eclipse.org/projects/eclipse.platform/who).

**Comment by vogella** [comment]
I will check and approve or reject tomorrow....

**Comment by marcushoepfner** [comment]
> > I would have expected the build (code freeze job) to tell me so.
> 
> Well, it obviously failing to fail the build. I've created [eclipse-platform/eclipse.platform.releng.aggregator#1079](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1079).
> 
> > But why is the code freeze job not failing in this case.
> 
> There were other fails which you shouldn't ignore either, like `check-merge-commits / Block Merge Commits`:
> 
> image
> 
> Please next time be more careful merging PR's.
> 
> Note: this one still needs a `project lead or PMC vote on the bug report`, otherwise it should be reverted so it doesn't add any regression during RC time.
> 
> I'm overcommitted with other tasks to perform the review here and vote for reverting it, so please if you want thos PR be in the RC1, please ask someone else to approve (see https://projects.eclipse.org/projects/eclipse.platform/who).

Did not see the block/merge commit. I waited for the jobs to finish. There were fine, except a flickering test which was not related to this commit. Then I got an "Update" button (guess main branch has diverged). I clicked on it and github told me, everything is fine, no further actions needed. So I merged. Since I know I had two commit now due to the branch update, I selected "Squash and merge". I've never seen the "block merge commits" failed.

**Pull request merged**
