### PR TITLE
Remove batik includes from the org.eclipse.e4.rcp feature

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1199

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse @akurtakov 

It looks like builds are taking so long (> 60 minutes) such that they abort.  😱

**Comment by mickaelistria** [comment]
I've tried #1193 about build duration, but it appears there could be a real issue to fix somewhere instead of just increasing timeout.

**Comment by laeubi** [comment]
You can always rebase this PR and look at the output to find out what takes the time:

- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1153

**Comment by merks** [comment]
I kicked another build manually and that completed and passed in 51 minutes.  That’s close to timeout.

**Pull request merged**
