### PR TITLE
Add close button to find/replace overlay #1991

### PR DESCRIPTION
**Pull request by HeikoKlare**
The find/replace overlay can currently only be closed via pressing Escape or using the shortcut CTRL+F when the overlay has input focus. This change adds a close button to the overlay for providing an easy and comprehensible way of closing the overlay.

In order to be compatible with different themes on all OS, we can, unfortunately, not reuse some shared close icons (i.e., one already provided in the platform.ui plugins). The icon adopts the color scheme (i.e., the same shade of gray) of the existing search options buttons.

Contributes to https://github.com/eclipse-platform/eclipse.platform.ui/issues/1991

### How it looks like (Windows)
image
image

### Alternatives
As an alternative, this is how it looks like with a preceding separator. 
image
That would clearly separate the single closing operation from the preceding search operations, but in my opinion it bloats up the overlay providing a significant benefit. Still it would be great to have our opinions (on the alternative as well as the proposal in general).

### PR for images repository
The images (including the orignal SVG) are provided here: https://github.com/eclipse-platform/eclipse.platform.images/pull/80

### Relation to other PRs
If this is merged before #2030, that PR will probably need some adaptation for the considerations of the toolbars on size calculation.

### CODE REVIEW

**Review by HannesWell — APPROVED** [review]
Looks good to me. 

> That would clearly separate the single closing operation from the preceding search operations, but in my opinion it bloats up the overlay providing a significant benefit.

Agree on that. On first sight it would be nice to separate it, but since all buttons on the right of the first separator are some kind of control buttons, I think it is fine to group them all together.

**Comment by Wittmaxi** [comment]
Ia agree that we shouldn't separate the closing-button, a separator would just add more to visually process and does not add any clear benefit.

Code looks sound!

**Comment by Wittmaxi** [comment]
I have documented the second part of the issue (which was only documented in the trace of comments below)
here https://github.com/eclipse-platform/eclipse.platform.ui/issues/2033

**Comment by Wittmaxi** [comment]
I have documented the second part of the issue (which was only documented in the trace of comments below)
here https://github.com/eclipse-platform/eclipse.platform.ui/issues/2033

**Comment by HeikoKlare** [comment]
Thank you for your quick feedback!
I just found noticed that by adding the close button to the existing search tools bar, it will be hidden when the editor becomes too small. That's not intended, so I will update the PR with the close button placed in a different toolbar that is not hidden when space is limited.

**Comment by HeikoKlare** [comment]
I have updated the PR so that the close button will always stay visible (even in the most reduced configuration of the overlay).
find_replace_close

**Comment by vogella** [comment]
Look great, thanks

**Review by BeckerWdf — APPROVED** [review]
Looks good and manually test on macOS dark theme is fine.

**Comment by vogella** [comment]
This new close icon can also be used to update the ugly notification close API. See https://github.com/eclipse-platform/eclipse.platform.ui/issues/2035

**Comment by HeikoKlare** [comment]
I consider your positive feedback as a general approval, so I will merge this PR now. In case there are things to change/optimize, we can still do that as a follow-up, but I guess it's good to have an easy way to close the overlay provided as soon as possible.

The failing test is a known random failure (#926) and the freeze period check is just because of M1 promotion, which does not forbid merges anymore.

**Pull request merged**
