### PR TITLE
set deprecation=error / analyze #1628

### PR DESCRIPTION
**Pull request by jukzi**
AbstractKeyFormatter has deprecation warnings in workspace but none shown in Jenkins

https://github.com/eclipse-platform/eclipse.platform.ui/issues/1628

### CODE REVIEW

**Comment by jukzi** [comment]
@laeubi do you mean something like this?

**Comment by akurtakov** [comment]
In order to achieve workspace and cli builds warning parity there should be no overrides as explained in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1628#issuecomment-1926807026 . Tweaking per bundle warnings should affect both after that.

**Comment by laeubi** [comment]
> @laeubi do you mean something like this?

yes

**Comment by jukzi** [comment]
such test seems not to help as error fails fast

**Comment by laeubi** [comment]
> such test seems not to help as error fails fast

It does help as it shows you the issue is actually detected and your setting is taken into account.

**Pull request closed without merging**
