### PR TITLE
various javadoc fixes

### PR DESCRIPTION
**Pull request by jukzi**
reduce ecj warnings in workspace

### CODE REVIEW

**Comment by jukzi** [comment]
has to wait for https://github.com/eclipse-platform/eclipse.platform.ui/pull/1287 due to conflicts

**Comment by jukzi** [comment]
@akurtakov  @iloveeclipse ci failed with `Java heap space` on this small change

**Comment by iloveeclipse** [comment]
> @akurtakov @iloveeclipse ci failed with `Java heap space` on this small change

I would propose to create a ticket and discuss there possible solutions.

**Comment by jukzi** [comment]
Did it fail because the today changes in sum are as worse a a single big change and we will have to wait for another i-build so that this repo's build will work again?

**Comment by akurtakov** [comment]
> Did it fail because the today changes in sum are as worse a a single big change and we will have to wait for another i-build so that this repo's build will work again?

It is actually quite likely as all these bundle changes will be compared as long as they are not in the I-builds repo.

**Comment by jukzi** [comment]
unrelated test errors on linux

**Pull request merged**
