### PR TITLE
Remove deprecated NumberToStringConverter and StringToNumberConverter

### PR DESCRIPTION
**Pull request by vogella**
Planned API deletion
Removes dependency from icu in the databinding API and therefore enable the removal of the not-so-active-maintained library

### CODE REVIEW

**Comment by vogella** [comment]
@mickaelistria or @laeubi what does this error message mean?

Failed to execute goal org.eclipse.tycho.extras:tycho-eclipserun-plugin:3.0.0:eclipse-run (api-analysis) on project org.eclipse.core.databinding: Error while executing platform: Error while executing platform: return code=4, see content of /home/jenkins/agent/workspace/eclipse.platform.ui_PR-354/apiAnalyzer-workspace/data/.metadata/.log for more details. -> [Help 1]

**Comment by mickaelistria** [comment]
@vogella Did you "see content of /home/jenkins/agent/workspace/eclipse.platform.ui_PR-354/apiAnalyzer-workspace/data/.metadata/.log for more details." ?

**Comment by vogella** [comment]
> @vogella Did you "see content of /home/jenkins/agent/workspace/eclipse.platform.ui_PR-354/apiAnalyzer-workspace/data/.metadata/.log for more details." ?

I tried https://ci.eclipse.org/agent/workspace/eclipse.platform.ui_PR-354/apiAnalyzer-workspace/data/.metadata/.log and https://ci.eclipse.org/jenkins/agent/workspace/eclipse.platform.ui_PR-354/apiAnalyzer-workspace/data/.metadata/.log but got 404. What is the correct replacement for /home/jenkins in the above URL?

**Comment by vogella** [comment]
@wimjongman is WB using these once too?

**Comment by wimjongman** [comment]
I don't know. M1 has shipped, so we will see what happens when this is committed in the next release.

**Comment by mickaelistria** [comment]
> is WB using these once too?

No occurrence found in https://github.com/eclipse/windowbuilder/search?q=StringToNumberConverter

**Comment by akurtakov** [comment]
As per https://git.eclipse.org/c/platform/eclipse.platform.common.git/tree/bundles/org.eclipse.platform.doc.isv/porting/removals.html#n629 :
Support and/or usage of ICU4J is being gradually removed from internals. Wherever ICU4J is exposed in API it's being deprecated and scheduled for removal after June 2022 release.
<p>
For further details or to provide feedback on this change, see <a href="https://bugs.eclipse.org/bugs/show_bug.cgi?id=562582" target="_blank">bug 562582</a>.
</p>

**Pull request merged**
