### PR TITLE
Migrate tools to UI

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by laeubi** [comment]
Version bumps required:

> 14:07:59.182 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.core.commands: Only qualifier changed for (org.eclipse.core.commands/3.10.300.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (3.10.300.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.core.databinding.observable: Only qualifier changed for (org.eclipse.core.databinding.observable/1.12.100.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (1.12.100.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.di: Only qualifier changed for (org.eclipse.e4.ui.di/1.4.100.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (1.4.100.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.css.core: Only qualifier changed for (org.eclipse.e4.ui.css.core/0.13.400.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (0.13.400.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.widgets: Only qualifier changed for (org.eclipse.e4.ui.widgets/1.3.100.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (1.3.100.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.workbench3: Only qualifier changed for (org.eclipse.e4.ui.workbench3/0.16.100.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (0.16.100.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.urischeme: Only qualifier changed for (org.eclipse.urischeme/1.2.200.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (1.2.200.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.ui.ide: Only qualifier changed for (org.eclipse.e4.ui.ide/3.16.200.v20230214-1401). Expected to have bigger x.y.z than what is available in baseline (3.16.200.v20221024-2137) -> [Help 1]
> 14:07:59.183 [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.e4.tools.services: Only qualifier changed for (org.eclipse.e4.tools.services/4.9.0.v20230214-1116). Expected to have bigger x.y.z than what is available in baseline (4.9.0.v20210427-1802) -> [Help 1]

**Comment by laeubi** [comment]
I can try to provide a commit with the version bumps, but wondering if it is planned to merge this already in this release or next one and if one should wait with the version bumps then?

**Comment by akurtakov** [comment]
Let's handle this one in RC1 phase if possible.

**Comment by laeubi** [comment]
I have pushed the version bumps here:
https://github.com/laeubi/eclipse.platform.ui/tree/pr-602-merge-tools

**Comment by vogella** [comment]
Cherry-picked commit from @laeubi on top of the merge commit.

**Comment by vogella** [comment]
@akurtakov I forgot what we do with the eca failing check. Just ignore as the old commit did not follow the current process? It is still fine to merge the change this week?

**Comment by akurtakov** [comment]
Yes, ignore eca, it's irrelevant for old commits.

**Comment by vogella** [comment]
> It is still fine to merge the change this week?

Planning to merge this one soon. Any objections @akurtakov or @laeubi?

**Comment by akurtakov** [comment]
It would be best if it goes in today so it's early in RC1 phase.

**Comment by mickaelistria** [comment]
> I have pushed the version bumps here:

As I'm looking at the history, it seems like this commit did bump many versions for no clear reason (ie no payload change). Any idea what has caused that?

**Comment by laeubi** [comment]
Have not investigated this in detail sometimes its just different settings between the repos (e.g. compiler, included/ignored resources) there are still some merges pending so if you want feel free to investigate next time whats this is in detail, there are also some old actions run still there where the log-output might give some hints:
https://github.com/eclipse-platform/eclipse.platform.ui/actions?query=branch%3Amigrate-tools-to-ui

**Comment by laeubi** [comment]
Another option would be to checkout the commit before the version bumps, not sure if this works now a new release has started...

**Pull request merged**
